### ISSUE TITLE
strangeness with toolbar

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#100]
I did a global search called "reference genome" and I got a result for 2421 genomes which seemed reasonable, but I wanted to sort it so I clicked on the show toolbar link in the header, because i wanted to sort the search results.  I actually in hindsight don't think this is possible, but there should be some intuitive sorting of search results on the website (I know I can sort the excel file).  Also, it looks like I should be able to show/hide columns in the spreadsheet of the results, but that part of the header seems to be dead.

![screen shot 2015-03-23 at 3 39 32 pm](https://cloud.githubusercontent.com/assets/7661533/6790061/eac2623e-d172-11e4-8255-69d8dba138b4.png)

![screen shot 2015-03-23 at 3 44 20 pm](https://cloud.githubusercontent.com/assets/7661533/6790147/b8fb6a60-d173-11e4-8b2e-bca52d8e0794.png)

**Comment by hyoo** [comment]
I understand your point. But this page is designed to be like a google search, where you want to see a summarized information. You can do this work in following steps,
Organisms tab -> All Bacteria -> Genome List tab -> check "Reference" in left hand side filter.
This will give you more precise result. 

The global search result may give you whatever genomes that contain "reference" and "genome" in their metadata.

**Comment by rwill1** [comment]
Harry,  note that when you do "Show Toolbar" (after doing a Global Search) that the "Columns" part of the toolbar shows up as active but then you can't do anything with it.  This is true on production and beta.   I think it should be grayed out like the Tools and View sections of the Toolbar are?  And only Workspace, Download, and Help should be active?

**Comment by rwill1** [comment]
Jim, as for sorting the search results, I feel your pain.  This was generally my #1 issue when we were collecting suggestions for website "ease of use" changes at the beginning of the project.  Generally, I add to workspace so that I can see the results in a table and do what I want to do.   Note that this is also not easy because Select All only shows the results on the current pages, so you need to change the "table" size at the bottom to be large enough (or select in multiple batches) and then select all and then add to workspace .... then you can sort / etc.   We've talked in the past about allowing search results to be able to be viewed in table format as well as "Google-like" format....

**Comment by hyoo** [comment]
This was due to the fact that toolbar was shared with other lists (feature list or genome list, for example). I agree this grid option confuses users when they see the global search results (the google-like view). So, I have disabled the column section in the toolbar for the global search result.
