### ISSUE TITLE
I think that selection from heatmap is returning all genomes in PATRIC

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1038]
Look at the number of features returned when 88 were selected.
<img width="283" alt="screen shot 2016-10-10 at 3 59 24 pm" src="https://cloud.githubusercontent.com/assets/11475316/19249272/a0cd9ea6-8f02-11e6-9b38-893f4c55f1aa.png">

**Comment by ARWattam** [comment]
That was from clicking on the column head where the protein family was named, I get all the features in PATRIC.  However, when I make a selection using my mouse in the heatmap, it works just fine.
<img width="1169" alt="screen shot 2016-10-10 at 4 01 50 pm" src="https://cloud.githubusercontent.com/assets/11475316/19249368/312d38bc-8f03-11e6-8f45-4e0920748343.png">

**Comment by mshukla1** [comment]
I think the problem is that:
1. it takes too long for the feature list overview tab to load
2. and, while it is still loading, if you switch to features tab, it shows all features!!!

![screen shot 2016-10-10 at 3 07 56 pm](https://cloud.githubusercontent.com/assets/1236463/19249489/76e677e0-8efb-11e6-9dd2-c37c7ff9c6d0.png)

![screen shot 2016-10-10 at 3 08 45 pm](https://cloud.githubusercontent.com/assets/1236463/19249493/7a5c4558-8efb-11e6-8119-9b6a48243b8c.png)

**Comment by hyoo** [comment]
I think this happens when user changed tab before the overview page is loaded.

**Comment by rkenyon** [comment]
Found same problem on Pathway heatmap.  Got tired of waiting for the Feature List Overview page to finish loading, so switched to Feature List, and returned over 500M features.

**Comment by hyoo** [comment]
This was due to the #1055.
I send to the features tab, but Topic.navigation controller trims hash params, which result in overview page.
