### ISSUE TITLE
Bug in feature overview

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1092]
A couple of things. 
 -- the arrows heads are hollowed out on the small genes.  They should probably become smaller width-wise.

 -- somehow the gene names are popping up in a weird way above the arrows, if you want this it should be a mouse-over.  This is the first genome where I've seen this. 

 -- a repeat region should not have an arrow neither should assembly gaps (see second image)

![image](https://cloud.githubusercontent.com/assets/7661533/19400134/5f5b13a2-921a-11e6-8e5a-f027da3a33c7.png)

![image](https://cloud.githubusercontent.com/assets/7661533/19400436/d732e7c8-921b-11e6-92d8-d97e1b9bbb0b.png)

**Comment by hyoo** [comment]
1. Arrow: This was happened after I increase the total window from 3000bp to 5000bp. Now 7~800px was mapped to 10000bp, which resulted in a small feature to be a weird arrow. Yes, we can decrease the arrow size, but that could not be enough to resolve this issue, since one pixel renders 15bp. 
   I will work on this, but want to ask whether it is okay to decrease the window a little bit.
2. okay
3. but the gap HAS strand. I will talk to you in offline.

**Comment by hyoo** [comment]
1. resolved. see #1163 

and regarding 2,3
for further discussion. I label it help_wanted.

**Comment by mshukla1** [comment]
After the recent style changes, the viewer looks much better now and shows small features nicely.
