### ISSUE TITLE
Need to use RefSeq locus tags on genome browser

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1098]
You will see the problem here.  I searched for BAB2_1016, which was listed in a paper.  I am trying to find the intergenic region, where there is a specific sequence that I want to see.  I open the genome browser and....Where is it?  I see the name at the top of the page, but instead of seeing the RefSeq locus tag I was searching for, I see a protein accession number.  I don't know the protein accession number for this feature.  Totally confused.  Mouse over, and can't see anything.  To quote The Donald,,..."sad"
<img width="1371" alt="screen shot 2016-10-15 at 10 56 09 am" src="https://cloud.githubusercontent.com/assets/11475316/19410974/6943cc86-92c6-11e6-8419-0dd2191b8976.png">

**Comment by aswarren** [comment]
This is not a bug. Especially since we discussed this before the workshop and decided to see what people thought about it. That being said, this is easily changed.

**Comment by ARWattam** [comment]
What they want to see are the RefSeq locus tags.  They don't like the accession numbers.

----- Original Message -----

**Comment by mshukla1** [comment]
Fine, not a bug if it was intentional to get user feedback. However, we have the feedback from users now, so it needs to be changed to RefSeq locus tags. -MaulikOn Oct 19, 2016, at 8:33 AM, Andrew Warren notifications@github.com wrote:This is not a bug. Especially since we discussed this before the workshop and decided to see what people thought about it.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/PATRIC3/patric3_website","title":"PATRIC3/patric3_website","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/PATRIC3/patric3_website" class="">https://github.com/PATRIC3/patric3_website</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@aswarren in #1098: This is not a bug. Especially since we discussed this before the workshop and decided to see what people thought about it."}],"action":{"name":"View Issue","url":"<a href="https://github.com/PATRIC3/patric3_website/issues/1098#issuecomment-254798663" class="">https://github.com/PATRIC3/patric3_website/issues/1098#issuecomment-254798663</a>"}}}
