### ISSUE TITLE
Top nav: change "Your" to "My"

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1107]
In the top navigation bar under workspaces [and probably other places as well], it says 
"Your workspaces" / "Your jobs" etc. 

I think it should be changed to "My workspace" / "My jobs" / "My genomes" etc instead. 

-Maulik

<img width="285" alt="screen shot 2016-10-17 at 5 09 50 pm" src="https://cloud.githubusercontent.com/assets/1236463/19457708/31fff704-948d-11e6-88f9-b92cd44a91c5.png">

**Comment by hyoo** [comment]
Discussions regarding "My vs Yours"

http://ux.stackexchange.com/questions/4348/your-vs-my-in-user-interfaces?atw=1

https://medium.com/@jsaito/is-this-my-interface-or-yours-b09a7a795256#.jwqos6v56

**Comment by mshukla1** [comment]
Harry, Thanks for sharing the link. 

If it was a conscious decision to use "Your" instead of "my", I am ok with it, as long as we be consistent in our use throughout the site.

**Comment by hyoo** [comment]
Your ticket just reminded me the links I read recently. I think there is no "Truth". My points were
- It isn't just us struggling "my" vs "yours"
- this could be something we can ask users during the beta test.

**Comment by nconrad** [comment]
I'd vote for "my" because it's personal, shorter, and isn't a response from the interface in this case.  I think it works particularly well with data when there's "my data", "shared with me" and "public".  People also can naturally report bugs and talk about their data the way it is reflected in the UI.  I.e., "There's a file missing under my data", "I see it's shared with me", etc.

In summary, I don't really see a benefit to "your".
