### ISSUE TITLE
Assembly file upload: nothing happened

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1118]
This happen to Rebecca during the workshop. 

-Maulik

**Comment by dmachi** [comment]
There isn't much detail to go on here.  The upload that I remember failing for rebecca at the workshop was trying to upload two files into single file selection box, which was the problem there.  That should indeed be fixed.  This is a workspace issue.

**Comment by dawenx** [comment]
@dmachi so the problem was: when a user chooses to upload read file 1 and read file 2 using the same file to a same location? i was able to reproduce it in the production and the 2nd try was not selected (after i chose to overwrite).

when i tested it in my local dev, this is working -- i think this a bonus of recent fix in file upload.

**Comment by mshukla1** [comment]
Dawen, I am not sure how to test this issue on alpha or production. Perhaps you can show it to Rebecca, so that she can verify. 

-Maulik
