### ISSUE TITLE
File type does not display for reads but does for contigs

### ISSUE THREAD

**Issue by brettin** [PATRIC3/patric3_website#113]
Browser is safari 7.1.3

![screen shot 2015-03-25 at 9 23 51 am](https://cloud.githubusercontent.com/assets/991769/6825395/aeaead98-d2d0-11e4-8584-2cd8fb4ca5cd.png)

**Comment by brettin** [comment]
On mouse over, the rhodo files indicate unspecified document type. However, these were identified as type reads when submitting an assembly. The file underneath the tooltip is a contigs file, and on mouse over it properly displays the type contigs.

**Comment by brettin** [comment]
The same appears true for the differential expression file types, that they are displayed as an unspecified type.

![screen shot 2015-03-25 at 9 23 51 am](https://cloud.githubusercontent.com/assets/991769/6826200/20043670-d2d6-11e4-866e-2226e11f91f5.png)

**Comment by dmachi** [comment]
This happens when there is no icon defined for a specific type (we don't have unique icons for all of them yet), so it defaulted to the file icon with "unspecified" as the type.  If changed the default behavior such that the icon is still the file icon when nothing else is defined, but the tooltip defaults to using the object's type property if defined.  Will be pushed to beta later this evening.
