### ISSUE TITLE
genome filter with isolation country and collection year

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1142]
it works when you select year (2011) and choose countries,

but does not work when you select countries first and collection year.

during the workshop. Ecoli example.

**Comment by mshukla1** [comment]
I was able to reproduce the problem. 

The problem is, when I select two countries first and then select year, all three filters get combined with AND instead of having OR for multiple filters for the same attribute. 

In fact, this problem appears any time I select multiple values of an attribute first (OR) and then select a value for another attribute (AND). 

https://www.beta.patricbrc.org/view/Taxonomy/561#view_tab=genomes&filter=and(eq(isolation_country,%22Norway%22),eq(isolation_country,%22United%20States%22),eq(collection_year,%222011%22))

<img width="1126" alt="screen shot 2016-10-24 at 11 55 54 am" src="https://cloud.githubusercontent.com/assets/1236463/19655341/24b90938-99e1-11e6-8a43-1757bc4d2662.png">

**Comment by dmachi** [comment]
This has been fixed and will be on alpha soon.

**Comment by mshukla1** [comment]
fixed. verified on alpha.
