### ISSUE TITLE
Refseq link for fig|1262684.3.peg.1312 doesn't go anywhere

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1160]
The refseq locus link for this feature doesn't get to a refseq feature page
"The following term was not found in Gene: BN575_01092."

https://www.beta.patricbrc.org/view/Feature/PATRIC.1262684.3.HF999589.CDS.29690.30529.fwd

**Comment by mshukla1** [comment]
Interestingly, the gene is in nucleotide/genome record and protein record, but not in the gene database!! 
https://www.ncbi.nlm.nih.gov/nuccore/CBBH010000108.1
https://www.ncbi.nlm.nih.gov/protein/524253444

It seems NCBI is not adding all the genes to gene database. Need to figure out how to link to them.

-Maulik

**Comment by mshukla1** [comment]
From NCBI: 

_Mon, 15 Sep 2014
Changes coming for representation of prokaryotic genes
We are planning to change the representation of prokaryotic records in Gene over the coming year to adjust to the explosion in sequencing of new bacterial strains. In the past, Gene has represented prokaryotic genes from all complete genomes and ignored draft (WGS) genomes because of low sequence quality. This has resulted in an over-representation of genes from some species, primarily human pathogens, whereas other prokaryotic species have not been represented at all because of lack of a finished genome sequence.

The RefSeq project is now defining reference and representative genomes to use as a standard baseline for comparison while continuing to provide genome annotation for all bacterial strains, including disease outbreak isolates, to support surveillance and testing needs (Tatusova et al 2014, PMID 24316578). To accommodate this expansion, Gene will focus primarily on content for reference and representative RefSeq genomes for prokaryotes, including draft genomes, in order to reduce intra-species record redundancy and also include species currently missing from Gene. NCBI's prokaryotic annotation pipeline is also exploring methods to provide shared GeneIDs for equivalent loci on all genomes annotated for a given species in order to provide access to relevant gene information for non-reference/representative RefSeq genomes.

In the first round of updates, we will be discontinuing records for non-reference/representative prokaryotic genomes, or in some cases marking records as replaced by their equivalent GeneID from a reference or representative genome from the same species. This will result in a large decrease in the number of prokaryotic GeneIDs and NCBI TaxIDs currently represented, which should make it easier for users to find the records of most interest. A comprehensive history of record replacements is available in the gene_history.gz file on the Gene FTP site at ftp://ftp.ncbi.nih.gov/gene/DATA/.

A second round of updates will add representative prokaryotic WGS genomes to Gene, increasing the taxonomic breadth of records.

These changes are expected to begin in the next month._

**Comment by mshukla1** [comment]
I guess we have two options: 
1. Remove the gene links for all non reference/representative genomes. 
2. Keep the links as is. The NCBI page says no records in genes, but provides links to matching records in nucleotide db, which might be useful to the users. 

Preference? 

-Maulik

**Comment by dawenx** [comment]
this issue is not there any more as below link goes somewhere, suggest to close it. https://www.patricbrc.org/view/Feature/PATRIC.1262684.3.HF999589.CDS.29690.30529.fwd
