### ISSUE TITLE
"upload your transcriptomics data" from e.g. Yersinia Transcriptomics tab / page

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#117]
not blocker imho

e.g. starting at https://www.beta.patricbrc.org/portal/portal/patric/ExperimentList?cType=taxon&cId=629&kw=
When I  click on the Upload your transcriptomics data link, I get login prompt on a page, not on a modal.   Do we care?

Also, the old login pop-ups (either for upload transcriptomics, or add to workspace) gave me the option of EITHER logging in or registering.   The new modal only allows login and doesn't offer the registration option, do we want to offer that link in the modal? (mixing my metaphors)

**Comment by dmachi** [comment]
This is intentional because that page can't load without auth.  

I  have not been putting the "register" link in the auth dialogs because then the actual registration would occur within.  However there is a register link in the top right of the page in all of those cases, so we could point that out in the login panel if you think that is better.
