### ISSUE TITLE
Jobs list maxes out at 1000

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1179]
I have way more than 1000 jobs in this account.

![image](https://cloud.githubusercontent.com/assets/7661533/19772847/1da4c184-9c2d-11e6-854e-6bffe78a6175.png)

**Comment by mshukla1** [comment]
I am changing this from critical to enhancement for the following reasons. 

- The same problem is also there ion the current production site. i.e. the problem is not specific to the new site. 
- This would be a problem only for a very small number of PATRIC users, as not many users will have more than 1000 jobs submitted so far. 
- In fact, I believe, this is mostly a problem for me, Jim and very few external users, if any. 
- The problem is not critical to any of the use cases / workshop tutorials for most users. 

-Maulik

**Comment by dmachi** [comment]
Fixed.  Limit is 10k now.  Will likely get slower the more jobs there are.  Need to address that in the future.
