### ISSUE TITLE
Bad Bug in genome browser

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1211]
I am doing an analysis where I need to look at contig 162 but it only allows me to select from the first 100 contigs.

Also it still bothers me that the original contig names are not retained.  I have no assurance that my contig 162 is the patric contig 162.

![image](https://cloud.githubusercontent.com/assets/7661533/19933602/f263f0f8-a0e1-11e6-95b5-c4392d8a17ab.png)

**Comment by mshukla1** [comment]
We discussed this yesterday. Increasing the number of contigs displayed in the dropdown will not help as there are genomes with more than 1000 contigs. 

@aswarren, We decided that we will provide links to genome browser from the sequence table. So, if you like to see a specific contig in genome browser, you can go to sequences tab, search for you contig of interest, and then jump top genome browser from there. 

I will see if we can change the data processing pipleine to retain original contig ids as labels or descriptions, so that they can be displayed in the sequence table and made searchable. 

-Maulik

**Comment by aswarren** [comment]
The immediate bug with the drop down limit has been fixed. The suggested implementation requires further discussion.

**Comment by mshukla1** [comment]
@hyoo In the sequences tab, when a single sequence is selected, provide link to the genome browser...similar to the one you provided from the contig blast.

**Comment by dmachi** [comment]
This really should be a Sequence View with Genome Browser tab within.

**Comment by aswarren** [comment]
Implemented in https://github.com/PATRIC3/p3_web/pull/310
@mshukla1 Thats not really what I meant by discussion.
