### ISSUE TITLE
download genome table

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1221]
I downloaded a table of genomes and the file was saved in my downloads as "patric3_genome_query-3.txt".  I then had to go back and download another list of genomes but it downloaded with the same file name, so now I can't just drag it to my desktop.  I'm using safari.

 
![image](https://cloud.githubusercontent.com/assets/7661533/19981959/09e1d66e-a1d2-11e6-916b-65523335e759.png)

**Comment by mshukla1** [comment]
This is another site wide issue. We need to use proper/consistent naming scheme for all file downloads. My recommendation is to use something like 

PATRIC_tabname_[optional:format]_date.ext 

Here are few examples: 

PATRIC_genomes_20160101.txt
PATRIC_sequences_20160202.csv
PATRIC_features_20160303.xls
PATRIC_protein_families.xls
PATRIC_transcriptomics.xls
PATRIC_transcriptomics_genematrix.xls

I am assigning it to everyone, so that you can address it in your functionalities.
