### ISSUE TITLE
Not able to upload bam file to genome browser

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1244]
Does this work?

**Comment by ARWattam** [comment]
And are we planning on enabling it?  I'm working on the tutorial and am wondering if I should leave it out or not.

**Comment by dmachi** [comment]
As I understood it, this does work.  In the genome browser you go to File->Open and you can upload a file as  an additional track.

**Comment by ARWattam** [comment]
I tried it.  It is not working.

----- Original Message -----

**Comment by aswarren** [comment]
There is a long and painful history why this isn't working. 
(and this will be the last time I explain it so help me)
We modeled our fasta headers after NCBI: >accn|CP001362
Such that our fasta headers don't match the sequence ID's for our GFF or our internal reference scheme (JBrowse and elsewhere): CP001362
Refseq recently de-dumbed their FASTA files so that now the ID's match.
We haven't caught up. This was an issue in RNA-Rocket with all the BRCs & is a consistent issue with software processing our FTP files. I've been trying to get us to do this for a while (and we even did for a little while).
What needs to happen here is I will patch JBrowse to support both our old-dumb reference scheme for backwards compatibility and the more reasonable one. And (eventually) the API AND FTP file generation procedure needs to be changed to take out that ridiculous prefix.

**Comment by aswarren** [comment]
So in essence. Your BAM would work if you convert it to SAM and fix all the labels then convert it back to BAM. 
Or you can wait to see if I can figure out a Jbrowse patch.

**Comment by aswarren** [comment]
This is fixed assuming you have both the *bam & *bai files.
