### ISSUE TITLE
Why aren't all the PLFams showing up in the PFS?

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1278]
I'm looking at Lactobacillus brevis ATCC 367.  When I look at the genome landing page, it says that it has 2271 PLFams:
<img width="1119" alt="screen shot 2016-11-16 at 4 12 54 pm" src="https://cloud.githubusercontent.com/assets/11475316/20366118/ba29bea2-ac17-11e6-9b2e-68bc373d2313.png">

But when I'm using the PFS and insist that each protein family contain Lactobacillus brevis ATCC 367, it says there are only 2211 PLFams:
<img width="1082" alt="screen shot 2016-11-16 at 4 14 55 pm" src="https://cloud.githubusercontent.com/assets/11475316/20366176/efc210a0-ac17-11e6-820c-436f84d4a651.png">

Am I missing something here?  Where are the other 60 PLFams?

**Comment by mshukla1** [comment]
Because the genome page summarizes "Proteins with PLFam assignments" while the PFS table shows the "Number of families". Many families have mire than one member. 

<img width="537" alt="screen shot 2016-11-17 at 6 31 53 pm" src="https://cloud.githubusercontent.com/assets/1236463/20413746/51f3299e-acf4-11e6-8f1b-a7285d6cda66.png">

<img width="1121" alt="screen shot 2016-11-17 at 6 32 15 pm" src="https://cloud.githubusercontent.com/assets/1236463/20413750/558b99ec-acf4-11e6-9ab1-2e29285d6419.png">
