### ISSUE TITLE
suggestion on filtering

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1286]
I know that all the available filters are displayed in alphabetical order, but I always find myself scrolling all the way to the right to get reference or representative genomes. I also think that public/private is more important than most of the other filed. I'm not sure that we should reorder these, but we should discuss it.

![image](https://cloud.githubusercontent.com/assets/7661533/20440227/bf125154-ad84-11e6-96eb-79f51f4ae852.png)

**Comment by mshukla1** [comment]
I agree. I propose we order the filters the same way they are on the production site, i.e. 

Public
Genome Status
Reference Genome
Antimicrobial Resistance
Isolation Country
Host Name
Disease 
Collection Year
Completion Date

**Comment by mshukla1** [comment]
I also suggest that we remove Antimicrobial resistance evidence, as it is not much useful, 
given most of the data is using AMR panel.

**Comment by dmachi** [comment]
I can remove that facet, but I don’t want to manually order them for this release.  We can discuss for the next release.  If we want to manually order, it makes things much more brittle and also means that we’ll need to go in and define that for all of the filters across the site.  I also believe this to be a relatively minor issue that exists in a small (though common) case.  This problem is generally only visible on the genome table and when there are no filters applied, so I think the proposed solution is overkill and more work than it is worth for this release.

My plan to address this in the future was slightly different;  We identify (when and where we want) a list of facets that will get pulled to the front of the list and possibly rendered in a processed way.  For example, we could pull the “Public” item to the front and render it as a switch or dropdown or using different text and something similar for Reference/Representative.  Those items not specifically called out for a particular filter set would remain in alphabetical order.

**Comment by mshukla1** [comment]
As of now, this is a problem only for the genome list, all other tables are 
fine as there are not many filters. 

However, genome list is where the filters are most useful and the most useful filters, 
public/private and reference/representative, are at the very end, making it likely 
that users will either miss them or will have to scroll every time they want
use them. 

Having said that, I it is an improvement and not a bug, so, I leave it to your 
judgement to decide whether to move them for November or not depending 
on the work involved. 

-M

**Comment by dmachi** [comment]
> As of now, this is a problem only for the genome list, all other tables are 
> fine as there are not many filters. 

Yes, thats what i meant when i said it is only visible on the Genome Table.  

> However, genome list is where the filters are most useful and the most useful filters, 
> public/private and reference/representative, are at the very end, making it likely 
> that users will either miss them or will have to scroll every time they want
> use them. 

They will only miss them or have to scroll only if they want to filter on those items first.  If they filter on anything else first, the list almost always shrinks and then generally shows those columns.  

> Having said that, I it is an improvement and not a bug, so, I leave it to your 
> judgement to decide whether to move them for November or not depending 
> on the work involved. 

I’m in agreement that this should be changed.  What I don’t want to do is reorder them with a list that would need to be defined for all the tables (they all use the same widget for this functionality).   Since we need to make things like the public/private and Representative look different anyway, I would prefer the implementation to do something slightly different than what you suggested.  I just don’t think we can get that all done for this release.  So my preference is to punt on this, relatively minor, issue until it can be fixed properly.

> -M
>

**Comment by mshukla1** [comment]
No worries. I will move it to March.

**Comment by chmao1** [comment]
Fixed it and made a pull request.

Removed the alphabetical sorting for the categories appear on the filter panel. The order of the categories can now be specified. This is also applied to other pages such as Features, Specialty Genes, Pathways and Transcriptomics. The order of the categories for these pages are the same as the Legacy PATRIC site.

**Comment by hyoo** [comment]
![image](https://cloud.githubusercontent.com/assets/1236467/25009024/efb79f08-202a-11e7-976d-dbbaa6ee7b07.png)

verified.
https://www.patricbrc.org/view/Taxonomy/234#view_tab=genomes
