### ISSUE TITLE
Unable to download fasta files from private genome-zip file empty.

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1299]
This is true in both production and on beta.  I go to the download tool and select protein fasta (I'm trying to build trees).  It downloads an empty zip file from each site.  Public genomes work okay, though.
<img width="517" alt="screen shot 2016-11-27 at 3 23 35 pm" src="https://cloud.githubusercontent.com/assets/11475316/20651543/83890f96-b4b5-11e6-8386-cc08c508a238.png">

**Comment by ARWattam** [comment]
I thought I would be able to select all the CDS features and download them as fasta from the genome page, but I couldn't do that either.  Totally stuck, and very unhappy.
<img width="1200" alt="screen shot 2016-11-27 at 3 28 57 pm" src="https://cloud.githubusercontent.com/assets/11475316/20651598/56b2450e-b4b6-11e6-94a4-3438f1408441.png">

**Comment by dmachi** [comment]
For the first part of your ticket, this is known.  The download comes from the FTP site.  We cannot put the private genomes on the ftp site, so therefore the private genomes dont' work via this method just as they don't on production.  However since they were private genomes you uploaded, all of the generated files should be available in your workspace in the Job Result.  It is ultimately planned to make this work, but requires serializers for each data type to be written and that hasn't been done yet.

The second part of your ticket is because the selection is >5k rows.  I don't remember where the 5000 number came from, the download limit there can probably be increased to 10k.

**Comment by ARWattam** [comment]
Thanks!

----- Original Message -----

**Comment by hyoo** [comment]
1. regarding the private genome, see #1432, #1470

2. download limit has been increased to 10k. This change will be deployed soon.
