### ISSUE TITLE
Make read library selector widget

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#1306]
This is being used in multiple apps Variation, RNA-Seq, Assembly.
Needs to be made into a single widget.
RNA-Seq probably has the most complete version since it has conditions.

**Comment by dawenx** [comment]
i'm planning to work on it.

**Comment by mshukla1** [comment]
@dawenx is this doen already? Can we close it?

**Comment by dawenx** [comment]
no, i only started to look into it a while ago and decided to stop at the time. having a single widget to support all read library selector turns out to be quite complex, especially in the case of RNA-Seq, etc. i would suggest to defer issues in this nature to p4 as they normally require design, implementation, testing and they affect large number of services even though user might not notice/appreciate the change at all. just my 2 cents.

**Comment by mshukla1** [comment]
Ok, as long as we are we are making them consistent across all relevant apps, I am fine with it.

Closing the ticket.
