### ISSUE TITLE
Genome group not showing up for Comparative Pathway Viewer either

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#136]
Same thing as with the PFS...only the old groups

**Comment by hyoo** [comment]
I cannot reproduce this problem. Exact same path #135

**Comment by hyoo** [comment]
This was due to the genome folder (output of genome annotation) in the genome groups folder. Not sure whether this is a right place to put the annotation result. Anyway, I have added condition to check only ObjectType=genome_group can be included in this request. This fix is available on alpha and will be deployed in bug fix release.
