### ISSUE TITLE
BLAST is misbehaving....drop down box persists

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1368]
I selected a blast program, but the stupid drop down box wouldn't go away and I couldn't select the database (because it was blocking it).  I re-selected to service from the tabs, and the BLAST program box came along with it.
<img width="881" alt="screen shot 2016-12-08 at 5 38 20 pm" src="https://cloud.githubusercontent.com/assets/11475316/21030590/6a00ec18-bd6d-11e6-9ae1-1edb72b3980b.png">

**Comment by hyoo** [comment]
ok, I found the way I can reproduce. here is the steps,
1. paste sequence
2. it will open up the program drop down.
3. modify sequence while the drop down is opened
4. scroll page, then the drop down layer will be detached from the dropdown box.

Dustin, this is a bug from Dijit. Do you know whether they have fixed in newer version? I think our dojo version is outdated(Dec 2014).
