### ISSUE TITLE
Bug in Annotation service

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1369]
I cannot upload a file with a .fasta file extension. If i change it to .fa, it will upload. 

Actually, when I try to upload from the folder icon, on the annotation app it doesn't work at all:

![image](https://cloud.githubusercontent.com/assets/7661533/21081604/3a3e2d86-bf90-11e6-9e8c-a9269b6b1566.png)

**Comment by dmachi** [comment]
I’m not seeing this problem.  Was able to upload fasta file with no problems.  What file type (contigs, reads, etc) did you assign the upload?  Are you sure there wasn’t already a file with that name where you were trying to upload?  We don’t currently do a good job of letting the user know when an upload fails because a file with the same name already exists.

**Comment by dawenx** [comment]
@jimdavis1 can you double check to see whether you still have this problem? i was able to upload a fasta file, actually, i was able to upload any random file.
