### ISSUE TITLE
BLAST download table doesn't have hits in the order of the BLAST result table

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1418]
This is especially cruel.  As the table doesn't have details on the hits, when you download it you expect it to be in the order that they appeared in the table you saw.  So if you are LABORIOUSLY adding in the coordinates of the genome sequences, you have to look very carefully to see that the table downloads in its own order.  Thankfully I caught it, but don't expect others to.

**Comment by hyoo** [comment]
![image](https://cloud.githubusercontent.com/assets/1236467/22609190/dba45ac8-ea25-11e6-861a-dc9ceb827d32.png)

I am not sure whether we're referring the same download. You should click the Download button on top of the grid to download what you expected (or described)

**Comment by hyoo** [comment]
now i see you meant "mapping coordinates of the genome sequence". let me see.

**Comment by hyoo** [comment]
I added hit_from and hit_to columns on both grid and download files. 

- ffn search
![image](https://cloud.githubusercontent.com/assets/1236467/26428247/4252bb1c-40a6-11e7-8be7-b800f31ec126.png)

- fna search
![image](https://cloud.githubusercontent.com/assets/1236467/26428295/7a0f9584-40a6-11e7-8c75-a27e96664543.png)

This two columns will be hidden by default, due to the space limitation, but should show up in downloaded file.
