### ISSUE TITLE
Cant search for genome name

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1423]
I cannot construct a clean search for "Agrobacterium" genomes using the search bar or the filters.

![image](https://cloud.githubusercontent.com/assets/7661533/22430528/32e66a56-e6d4-11e6-9cd7-e8339e14906c.png)

**Comment by hyoo** [comment]
there were some matches on comment field and some on taxon lineage field like below,
```
"taxon_lineage_names":["cellular organisms",
          "Bacteria",
          "Proteobacteria",
          "Alphaproteobacteria",
          "Rhizobiales",
          "Rhizobiaceae",
          "Rhizobium/Agrobacterium group",
          "Rhizobium",
          "Rhizobium mesoamericanum",
          "Rhizobium mesoamericanum STM6155"],
```
```
"biosample_accession":"SAMEA3522225",
        "comments":["Ruegeria atlantica is a member of the family Rhodobacteraceae reclassified in 1998 by Uchino et al. as a gen. nov. comb. nov. of Agrobacterium atlanticum, described in 1992 by R�ger et. al. Genome sequencing of Ruegeria atlantica CECT 4293 was done using the Illumina Miseq system by the Central Service of Support to Experimental Research (SCSIE) of the University of Valencia (Spain)."],
        "genome_length":4825935,
```

**Comment by dmachi** [comment]
This search is correct.  The other items are showing up in the search results because either “Agrobacterium” is listed either in the comments or in the taxon lineage.  I think some of this is because of the renaming of the taxon.  From one of the Agrobacterium comments: “Agrobacterium tumefaciens (former name Rhizobium radiobacter)”
