### ISSUE TITLE
Nonsusceptible in AMR page

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1457]
It looks like we have a number of differences.  What does non-susceptible mean?  Is it resistant?  Is it intermediate?  If not, we need to define it because no one will know exactly what we are saying.
<img width="728" alt="screen shot 2017-03-31 at 9 39 02 am" src="https://cloud.githubusercontent.com/assets/11475316/24552842/12ecd66c-15f6-11e7-89eb-dca7bc9959eb.png">

https://www.patricbrc.org/view/Taxonomy/1301#view_tab=amr&filter=and(eq(antibiotic,Beta-lactam),eq(resistant_phenotype,Susceptible))

**Comment by mshukla1** [comment]
Non-suceptible is perfectly valid. There are few organisms, like Niesseria, that do not 
have clearly defined break points in CLSI or EUCAST. They are published with designation
of susceptible and non-suceltible. Both Jim and I have discussed this and decided to leave
it as non-susceptible, since it is accepted by the organism community. 

-Maulik
