### ISSUE TITLE
AMR regions need a link to the genome browser

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1458]
Although the location is defined, there is no direct link to the browser.  You can see it by going to the feature page, but the browser icon should be available in the mystical green bar.

**Comment by hyoo** [comment]
We decided not to expose all the possible linkouts, due to the limited space of action bar. However, we do have a functionality to keep the direct link, which is "press and hold". For example, go to

https://www.patricbrc.org/view/Genome/470.1738#view_tab=features&filter=and(eq(feature_type,%22classifier_predicted_region%22),or(eq(annotation,%22PATRIC%22)))

![image](https://cloud.githubusercontent.com/assets/1236467/25345373/87efcbee-28da-11e7-9de5-ae1826237ea5.png)

click the "Feature" button and hold it for a second, then you will see sub menus each corresponds to tabs in Feature view.

![image](https://cloud.githubusercontent.com/assets/1236467/25345391/92598e3a-28da-11e7-80ef-9e36697acec8.png)

**Comment by hyoo** [comment]
Task for @AndrewGuard 
We need to update this submenu since we have more tabs available. 

![image](https://cloud.githubusercontent.com/assets/1236467/25345591/1add7564-28db-11e7-9746-b53183b88757.png)

https://www.patricbrc.org/view/Feature/PATRIC.470.1738.LN865143.classifier_predicted_region.2070651.2070688.fwd#view_tab=overview

**Comment by ARWattam** [comment]
Ah....I've never done that.  Very useful, but do you think that other
people will be able to discover this on their own?

Rebecca

**Comment by mshukla1** [comment]
That is the mechanism we have for going to additional tabs and downloading data in various file formats, 
from pretty much every table on the site. 

If we think people won’t notice/discover, it is a design issue that needs to be addressed site wide…either 
by designing a better widget or by faqs/tutorial. 

-M

**Comment by hyoo** [comment]
agree, this is not a typical web UI. I like the idea of showing them in workshops and tutorials. Something we need to spread out.
