### ISSUE TITLE
Most, if not all, downloads from landing page for genome give empty zip files.

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1459]
https://www.patricbrc.org/view/Genome/1719.1833

When I select any of the files from the download button on the homepage (see screenshot and glaring red arrow), a zip file downloads, but when I try to open it, I get an error.  The size is wrong, too.

<img width="1071" alt="screen shot 2017-03-31 at 1 01 21 pm" src="https://cloud.githubusercontent.com/assets/11475316/24560848/5cc8ede0-1612-11e7-9555-8be9a50a5bc7.png">

<img width="923" alt="screen shot 2017-03-31 at 1 03 10 pm" src="https://cloud.githubusercontent.com/assets/11475316/24560879/7d78dc3a-1612-11e7-93ba-017c784888fb.png">

**Comment by dmachi** [comment]
What file types are you choosing when you do this.  The very first one I went to (https://www.patricbrc.org/view/Genome/1262770.3 <https://www.patricbrc.org/view/Genome/1262770.3>) worked fine.  I chose Genomeic Sequences in FASZTA and annotations in genbank format.  The resulting download had only the FASTA files (presumably because the public files don’t have genbank format any more)

**Comment by ARWattam** [comment]
The zip files don't open.  The TGZ files give me an error (see screenshot),
but they do unzip and give some data.  Zip format is the default.

I haven't checked all possibilities...should I?

**Comment by ARWattam** [comment]
Oh, and a user reported it, so its not just me.

**Comment by dmachi** [comment]
This behavior happens when the files aren’t actually in the ftp site.  Maulik indicated he has generated the ftp files for a bunch of the newer genomes, but hasn’t synced them onto the ftp site yet.

**Comment by hyoo** [comment]
after moving data api to ANL, we no longer needs to sync and this should work without sync. so i am closing this ticket.
