### ISSUE TITLE
Compare region viewer for AMR classifiers doesn't load

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1471]
I'm at this page:
https://www.patricbrc.org/view/Feature/PATRIC.1280.8888.FKLV01000003.classifier_predicted_region.282859.282919.fwd#view_tab=compareRegionViewer

All I see is the spinning wheel. 

When I open developer tools and look at console I get this message:

dojo.js:19 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
s.getText @ dojo.js:19
/public/js/jbrowse.repo/plugins/HideTrackLabels/js/main.js:40 plugin HideTracksButton constructor
https://www.patricbrc.org/api/jbrowse/genome/1280.8888/names/?equals=FKLV01000003%3A279859..285919 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
/js/3.3.0/p3/layer/core.js:2991 Uncaught TypeError: Cannot read property 'reference_point' of undefined
    at Object.render (/js/3.3.0/p3/layer/core.js:2991:464)
    at Object.resize (/js/3.3.0/p3/layer/core.js:2990:324)
    at Object.eval (/js/3.3.0/p3/layer/core.js:2988:402)

**Comment by hyoo** [comment]
Yes, because this is classifier_predicted_region and missing attributes like pinned_peg and pinned_peg_strand. @olsonanl , do you think we should allow compare region viewer only for the CDS?

@ARWattam if you interested, you can go to the corresponding CDS and run the compare region viewer.
https://www.patricbrc.org/view/Feature/PATRIC.1280.8888.FKLV01000003.CDS.282675.283565.fwd#view_tab=compareRegionViewer

Instruction from your original page,
go to overview -> click the gene "hel" from the gene viewer -> click compare region viewer

![image](https://cloud.githubusercontent.com/assets/1236467/24662126/d8855158-1919-11e7-9329-62a0b6023903.png)

**Comment by olsonanl** [comment]
Yes - compare regions only makes sense for protein encoding genes. 

That is to say, we can only compute pins on protein encoding genes. It might make sense to allow users to select a non-CDS and have the service choose a neighboring region to pin on, but that is an enhancement.
