### ISSUE TITLE
services: ref/rep selector doesn't work

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#1514]
The genome selector in the services has filter options for the reference and representative genomes. 

However, when I select reference and representative and start typing genome names, it doesn't do auto complete or suggest matching names and keep complaining "Value entered is not valid". 

-Maulik

<img width="783" alt="screen shot 2017-05-17 at 1 23 46 pm" src="https://cloud.githubusercontent.com/assets/1236463/26169664/2f80aa82-3b04-11e7-8f73-4c4de6bb2989.png">

**Comment by aswarren** [comment]
Yes these should probably read "Reference Only" and "Representative Only" and be unchecked by default. Since the default behavior should always be to include them and the desired filtering is to get rid of everything but those.
This is how it currently looks.
![image](https://cloud.githubusercontent.com/assets/229173/26182777/592ef494-3b48-11e7-80c2-baa1ea93131b.png)

**Comment by aswarren** [comment]
![image](https://cloud.githubusercontent.com/assets/229173/26264807/1e388016-3cac-11e7-95e2-f91df555efa4.png)
![image](https://cloud.githubusercontent.com/assets/229173/26264827/328d4fa6-3cac-11e7-8ec3-365eb4163930.png)

**Comment by aswarren** [comment]
Fixed in https://github.com/PATRIC3/p3_web/commit/a6554354dfab4e190e81c27daf6673f2792ee1c4
