### ISSUE TITLE
Do not find any TBCAP Mtb annotations by searching "TBCAP"

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#1544]
Trying to find genes with structured assertions from the TBCAP jamboree, but search on "TBCAP" in search only returns genes in Homo sapiens.

**Comment by rkenyon** [comment]
For example, I would expect a link to the following feature page, which has TBCAP structured assertions:
https://www.patricbrc.org/view/Feature/PATRIC.83332.12.NC_000962.CDS.34.1524.fwd#view_tab=overview

**Comment by mshukla1** [comment]
Structured assertions are not part of the primary feature related data, hence they are not searchable from the global search as of now.  

If we want to add it, we will need to add it as another data type in the global search. It would be easy to add, however, given that structured assertions are available only for relatively small number of features, I am not sure if it is worth it! 

Let me know if you think otherwise. 

-Maulik

**Comment by rkenyon** [comment]
Changing to won't fix and closing.  Would be nice to have, but sounds like it is out of scope for now.
