### ISSUE TITLE
Still missing feature importance for classifiers

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1549]
![image](https://user-images.githubusercontent.com/7661533/27915477-22433408-622c-11e7-970b-844af472963e.png)

**Comment by hyoo** [comment]
#1284

**Comment by rkenyon** [comment]
Verified using Harry's examples shown in #1284

**Comment by hyoo** [comment]
@jimdavis1 would you try on alpha?

**Comment by rkenyon** [comment]
I think @jimdavis1 still needs to verify.

**Comment by mshukla1** [comment]
@hyoo 

For some reason, classifier score and classifier round are not displayed in the table, evern after adding those columns. I suspect it is because data API doesn't return those fields. Can you check and fix it ASAP?

Below is the URL for a genome that has such data. 

https://patricbrc.org/view/Genome/1313.15745#view_tab=features&filter=and(eq(feature_type,classifier_predicted_region),eq(annotation,PATRIC))

<img width="1360" alt="Screen Shot 2019-04-07 at 10 45 51 AM" src="https://user-images.githubusercontent.com/1236463/55686064-93815e80-5922-11e9-8614-54f6ec69a2f4.png">

**Comment by mshukla1** [comment]
@hyoo has updated the data API and UI. Classifier score and rank are displayed now. I have verified it on the production site. 

<img width="1365" alt="Screen Shot 2019-04-08 at 4 00 37 PM" src="https://user-images.githubusercontent.com/1236463/55756627-990ca080-5a17-11e9-97ae-15d25c4a77c6.png">
