### ISSUE TITLE
No side panel on smaller screen

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#1594]
On my 13" mac with a safari window nearly full screen (but for the dock) I don't get the right-side action bar, just the add to group icon peeking over things on the right.

![screen shot 2017-07-17 at 7 46 28 am](https://user-images.githubusercontent.com/2152226/28268505-21da2cec-6ac4-11e7-8a5d-a8614a972621.png)

**Comment by mshukla1** [comment]
We don’t have right side green action bar on the feature overview page! 

Did you attach the right screenshot or am I missing something? 

-Maulik

**Comment by olsonanl** [comment]
Hm. I guess I was expecting it to be there so that I could take actions on that feature.

**Comment by dmachi** [comment]
Since there is nothing to ‘select’ on that page, there is no green (selection) bar.  All of the actions available would be in that section where add to group is.  Additional actions (the equivalent to selecting a single feature on a Feature Grid) could be added to there to cover the other actions, but aren’t currently there.

**Comment by mshukla1** [comment]
The action bar usually works with the selection in tables and, as of now, there is 
no select function on the feature page.  

Single feature level actions, such as download na/aa sequences and add to group 
actions are available from the page in other ways. 

Did you have some specific actions in mind which not available on the page? 

-M
