### ISSUE TITLE
If I hit reset on the tree building service, I am unable to resubmit

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1631]
If one wants to resubmit the same groups and try all possible combinations for the tree building service (which I did), you can reset, but the submit button is not enabled when you do it.  This means you have to go away from the page, go back to Services-Phylogenetic trees, and start again.  Frustrating.
<img width="508" alt="screen shot 2017-08-10 at 1 57 55 pm" src="https://user-images.githubusercontent.com/11475316/29184453-3564db4a-7dd4-11e7-8d7b-51f2bcbd0c61.png">

**Comment by dawenx** [comment]
There's a problem in resetting and I will work on the fix, but you might not like my fix: generally the 'reset' is supposed to take you back to the same place as if the page had just been loaded. In another words, you have to fill in everything (including ingroup/outgroup) after you click on 'reset', is that OK?

**Comment by dawenx** [comment]
i decided to go ahead to fix 'reset' button and it will take user back to the same empty page as if the page is just loaded.

@hyoo can you 'approve' this plan before i do it? thanks.

**Comment by hyoo** [comment]
@dawenx that's what 'reset' button supposed to do. If it doesn't we should fix it. 
However, Rebecca's point is not that problem. I agree to fix the behavior of 'reset' button as expected. Go ahead. On top of that, we need to think about the Rebecca's scenario either.

@ARWattam I understand user may want to do that. So, in ideal situation, if users change some options as they wanted, then, should we reactivate submit button? However, this is not consistent to other submission form. As far as I know, like assembly or annotation, if your submits, we reset all the fields. What would be the expected behavior? keeping values in the form so that user can modify later or reset the values after submission?

**Comment by dawenx** [comment]
@hyoo currently the selected entries in both ingroup and outgroup are not cleared after someone clicks on 'reset'. i used "Proteome Comparison" service as the example for developing this UI and similar behavior is there as well. i talked to chunhong briefly today and she said that's intended behavior for that service. As discussed, I will go ahead to fix it for tree service so that 'reset' would reset everything. i will address Rebecca's scenario after we have agreement on what's the proper solution.

**Comment by dawenx** [comment]
the fix was deployed to production.
