### ISSUE TITLE
reference filter is not working properly

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/patric3_website#1639]
![image](https://user-images.githubusercontent.com/1236467/29285407-04a73ca0-80f4-11e7-856c-f219cc3855e5.png)

This was due to wrong query 
https://www.patricbrc.org/api/genome/?or(eq(genome_name,*mg1*),eq(genome_id,*mg1*))&and(eq(public,false),eq(public,true),eq(reference_genome,%22Reference%22))&select(genome_id,genome_name,strain,public,owner,reference_genome)

see the 2nd filter that public = false AND public = true AND reference_genome = "Reference"

public cannot be true and fault at the same time.

**Comment by hyoo** [comment]
This works.

or(eq(genome_name,*mg1*),eq(genome_id,*mg1*))&and(eq(reference_genome,%22Reference%22))&select(genome_id,genome_name,strain,public,owner,reference_genome)

**Comment by chmao1** [comment]
You can't uncheck Public Genomes and My genome at the same time. If both unchecked, no genomes are available. We should make sure that Public Genomes is checked when Reference or Representative filter is checked. This needs to be fixed.

**Comment by chmao1** [comment]
Please comment on whether the following changes are reasonable:
1) Apply logic OR for the check boxes
2) When "Public Genomes" is checked, all "Public Genomes" will be available for the genome list regardless whether "Reference Filter" or "Representative Filter" is checked.
3) When "Public Genomes" is unchecked, and "Reference Filter" or "Representative Filter" is checked, then, only Reference or Representative genomes are available for the genome list.

**Comment by zreyn** [comment]
Having looked into this before, it's generally quite confusing.  Also, the underlying data model isn't clear to me, so it may not be clear to users either.  Here's my assumption (which may ultimately not be correct): I assume that genomes are either Public or private (My Genomes) and that genomes may be tagged as Reference and/or Representative.

1.  Definitely reasonable. The original intent here was that the check boxes indicate what should be included in the results.  That's why not having either box checked had no results.  So, some wording like this (along with the forced OR logic) might do the trick:
[] Include Public Genomes
[] Include My Genomes

2. I'm not entirely sure about this... I think if the user has Public Genomes selected and then puts a filter on Reference/Representative they'd expect to see the intersection of Public and Reference (or the intersection of Public and Representative) genomes.  Your proposal sounds more like the Reference/Representative filters will be ignored.

3. Similarly here, if Public is unchecked (and based on #1 that My Genomes is checked) and Reference is checked, then you'd get the intersection of My Genomes and Reference.  Same for Representative.

Again, my understanding of the data might be wrong and Reference and Representative genomes somehow transcend the Public/private designation.

**Comment by zreyn** [comment]
Also, I haven't looked into whether this is possible, but some indication of how many genomes result from the filter combination might be helpful.  I say this because the concern over this seems to be around combinations of filters yields 0 results.

**Comment by chmao1** [comment]
Thanks for the comments @zreyn.  Reference/Representative genomes are public, so "Public Genomes" contains all Reference/Representative genomes. This makes it challenging to be clear about the meaning of the combination selections. I agree, some additional wording changes might do the trick. For example:
[] Include All Public Genomes
[] Include My Genomes
[] Include Reference Genomes
[] Include Representative Genomes
With this wording change, would no. 2 and 3 make more sense? Please recommend better wording or changes.

**Comment by zreyn** [comment]
Ahh, ok, I understand!  Yes, I like your wording suggestion; they should work well with your 2 and 3 above.  Go for it.

**Comment by chmao1** [comment]
I just discussed this issue with Rebecca and we both like the following idea for the checkbox selections. Initially, everything is checked. 

Public Genomes:
   [] Reference Genomes
   [] Representative Genomes
   [] All Other Public Genomes
Private Genomes:
   [] My Genomes

We'd like to hear some feedback. Thanks.

**Comment by chmao1** [comment]
Fixed and made a pull request.

**Comment by hyoo** [comment]
![image](https://user-images.githubusercontent.com/1236467/29879162-e9282674-8d69-11e7-9658-30ad6c79d860.png)

working as expected.
