### ISSUE TITLE
view button doesnt work for a genome that you don't have access to:

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1667]
The behavior is unclear

![image](https://user-images.githubusercontent.com/7661533/29576430-5b28576e-872d-11e7-87e4-1bad0e2e4afa.png)

**Comment by hyoo** [comment]
if we can add a check routine, before we display view button, this will also address issue that private genome is not available when it is in solr index queue.

**Comment by nconrad** [comment]
@hyoo, what would the check be?  All I can figure is a check for 403 forbidden vs a 500 server error?  https://p3.theseed.org/services/data_api/genome/562.18161 vs  https://p3.theseed.org/services/data_api/genome/1262708.3 ?

**Comment by hyoo** [comment]
i guess in this particular case, genome id is 573.12900 and we can query /genome/573.12900 to ensure genome has been indexed on solr.
Since this is a private genome, you also need to pass authorization token in header.

**Comment by nconrad** [comment]
I got the first url https://p3.theseed.org/services/data_api/genome/562.18161 via the public PATRIC Workshop workspace.  One of the corresponding requests says forbidden from the genome page (only in the console):


![image](https://user-images.githubusercontent.com/1194246/30334708-0040bfec-97a6-11e7-8550-60087ad19c70.png)

**Comment by hyoo** [comment]
okay, i misunderstood the original request. This happens when user shares their workspace with "PUBLIC". Sharing with public did not trigger changing genome (or any solr data) flag (public = true).

I was confused with other tickets saying when user clicks "view" button before the genome is indexed, the page was not available and user got frustrated. That's why I suggested a "checking" mechanism.

**Comment by nconrad** [comment]
There's at least be a message on the genome page now, explaining why the page can't be loaded.
