### ISSUE TITLE
Redirect to patricbrc.org after first login

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#1676]
After logging in here, user should be taken to patricbrc.org:

![i80 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/1194246/29678502-741f8a10-88c4-11e7-9a0d-4b90e1aa1f43.png)

They are currently brought here:

![i81 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/1194246/29678524-8da1a34c-88c4-11e7-98a8-e31b595f371a.png)

**Comment by nconrad** [comment]
@dmachi I assigned you, but feel free to reassign...

**Comment by dmachi** [comment]
I've updated p3-user on alpha so that it takes you to the patric home page after you change your password on registration instead of taking you to the account home page.  I believe this was the main case to take care of.  If you login from the user page itself, it will still keep you in the user site.

**Comment by hyoo** [comment]
@nconrad would you double check on production and close this ticket?
