### ISSUE TITLE
User unable to get all Vibrio cholerae genomes through download

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1681]
WE had a user with this problem.  Dustin looked into it, and he, too, could not get all of the genomes that should be available.  Here is what Dustin had to say:

"I browsed to that taxon at https://www.patricbrc.org/view/Taxonomy/666#view_tab=genomes, select all, click download on the green bar, advanced->selected .fna.  It successfully downloads, but looks like there are only ~500 of the genomes in there."

**Comment by hyoo** [comment]
Isn't it because of out-sync files? I will test and update.

- I tried on the page above, saying 729 genomes available, but downloaded 500 genomes.
- file sync may not be the source of problem. ftp site was synched on Aug 20 2017, but the most recent Vibrio cholerase genomes were indexed on July 23 2017. 
- I suspect data api now and will look into it

**Comment by hyoo** [comment]
https://github.com/PATRIC3/p3_api/blob/master/bundler/genome.js#L48

this was the reason that downloading only 500 genomes regardless of your selection. I will fix and deploy.

**Comment by hyoo** [comment]
fixed but we need to wait until the fix is deployed.
https://github.com/PATRIC3/p3_api/commit/e4033a7dbb26f352a7231a138871e872a10d3d3a

**Comment by hyoo** [comment]
This has been deployed on production.
