### ISSUE TITLE
I'm overwhelmed by the jobs overview page

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1735]
I need to delete or hide old jobs.  If that isn't possible, I'd like to group job status by the job directory in the workspace.

![image](https://user-images.githubusercontent.com/7661533/30975279-8d7f4994-a437-11e7-9421-dcd14e279f71.png)

**Comment by nconrad** [comment]
@jimdavis1 Does the "running" filter on the alpha site help with this issue? 

![image](https://user-images.githubusercontent.com/1194246/31684838-a141f544-b346-11e7-96d4-5cfd20fdf86c.png)

The main issue with this is that the jobs list is still limited to the last 10k jobs.  We should be able to increase this to 20k or so, but there's not much else that can be done without server side changes.

**Comment by nconrad** [comment]
this is on alpha

**Comment by nconrad** [comment]
whoops... I misread.  @jimdavis1 do you think this "fixed" on alpha?  It isn't exactly what you asked for, but may suffice for time being.

**Comment by mshukla1** [comment]
The new filters are helpful in finding jobs by types or status. 

However, both me and Jim, submit hundreds/thousands of assembly annotation jobs in batch mode, often in the same workspace folder, because they are part of single study. 

The problem is finding a specific job for follow up / looking at results. Currently the way I do it is by manually adding specific job id in the URL and go to that directory. It would be good if we have a way to search for jobs and / or workspace files by keyword. 

@jimdavis1 do you agree?

**Comment by hyoo** [comment]
Searching would be another task. I think people all liked current solution and this is already deployed on production last November 2017 release. Please create another ticket if you want extra feature.
