### ISSUE TITLE
User reports problems with ability to view shared workspace

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1747]
User ID: sviclittle

User says:
Also, members to the workspace can not access (view or edit) all of the
genomes-only the member that submitted job can see the results even if job
is saved in a shared folder.

**Comment by nconrad** [comment]
Assuming they are talking about the view button, this is correct.  I'm not sure what the fix for this would be.  We should talk about this, @mshukla1 , @hyoo, @dmachi ?

**Comment by mshukla1** [comment]
This is because, when you share a workspace, you share only the files and folders in those workspaces and 
not the indexed genomes. Those are still owned by and visible to only the owner. So, the users will be able to 
see the job result files, but will not see anything on corresponding genome pages, or won’t be able to see those 
genomes in the tables. 

Sharing a indexed genome with other users requires adding user names to appropriate records in solr.  

<field name="public"			type="boolean"		indexed="true"	stored="true"/>
<field name="owner"			type="string"		indexed="true"	stored="true"/>
<field name="user_read"			type="string"		indexed="true"	stored="true"	docValues="true"	multiValued="true"/>
<field name="user_write"		type="string"		indexed="true"	stored="true"	docValues="true"	multiValued="true"/>

I have a script that I have used in the past to share data among select users and collaborators. 
We need to wrap it up as a data API function and expose it through user interface. So that, users 
can select one of more genomes and share them with select users, just like how they share 
workspace content. 

-Maulik

**Comment by nconrad** [comment]
This was fixed with the addition of genome sharing.  We are testing sharing of more than 50 genomes now.
