### ISSUE TITLE
User requests to see amino acid position change in variant analysis

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1754]
Not sure how hard this would be, but seems like a reasonable request:
"It would be possible to get the position of the aminoacid change seen in the  table of variant analysis "

**Comment by mshukla1** [comment]
@maovt 

I believe the latest version of SNPEff tool and output format supports AA change position in the output. 
Can you please look into it and make necessary changes to the output snp tables? 


http://snpeff.sourceforge.net/SnpEff_manual.html#intro

HGVS.c: Variant using HGVS notation (DNA level)
HGVS.p: If variant is coding, this field describes the variant using HGVS notation (Protein level). Since transcript ID is already mentioned in ‘feature ID’, it may be omitted here.
cDNA_position / cDNA_len: Position in cDNA and trancript’s cDNA length (one based).
CDS_position / CDS_len: Position and number of coding bases (one based includes START and STOP codons).
**Protein_position / Protein_len: Position and number of AA (one based, including START, but not STOP).**

**Comment by chmao1** [comment]
@mshukla1, Currently, the Variation service uses EFF format (instead of ANN you mentioned above) for the annotation. Here is the EFF format: EFF = Effect ( Effect_Impact | Functional_Class | Codon_Change | Amino_Acid_Change| Amino_Acid_Length | Gene_Name | Transcript_BioType | Gene_Coding | Transcript_ID | Exon_Rank  | Genotype_Number [ | ERRORS | WARNINGS ] ) 

which has Amino_Acid_Change field like this: p.Leu675_Asp676fs/c.2025_2026insT

Would this information be good enough to show amino acid position change (plus nucleotide change)?

**Comment by chmao1** [comment]
Replaced columns Ref_aa and Var_aa with Ref_nt_pos_change and Ref_aa_pos_change. This feature is
available in production now.
