### ISSUE TITLE
Genome search result

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1766]
Can we blow away the two lines that are meaningless, 
SEQUENCED: 2014-12-08T22:11:50.753Z ( NIH Intramural Sequencing Center )
COLLECTED: 2011 HOST: Human, Homo sapiens
and add the genome identifier so I don't have to click and click and click?

![image](https://user-images.githubusercontent.com/7661533/32123835-579bdefe-bb2b-11e7-93fb-5aa29d4974bb.png)

**Comment by mshukla1** [comment]
Agree. We should add genome id. Actually, I am surprised no one has asked for it until now! :)

The other information is meant to provide some context so that you can identify the genome 
you are looking for without looking at top N hits one by one. The information displayed helps you 
quickly learn the genome was sequenced by whom, when and why. As there are more and more
 genomes with similar names, this information may come handy. 

-Maulik

**Comment by hyoo** [comment]
in addition to that, Sequenced date is wrong, it is using date_inserted.

![image](https://user-images.githubusercontent.com/1236467/32959045-f5058900-cb85-11e7-94ad-a0521866aba0.png)

http://www.patric.local/search/?keyword(pneumoniae)

**Comment by chmao1** [comment]
I'll add genome _id and correct the completion date.

**Comment by chmao1** [comment]
The fix is now available on alpha and production.

**Comment by hyoo** [comment]
confirmed.
