### ISSUE TITLE
Cant load data for a newly annotated genome

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1777]
![image](https://user-images.githubusercontent.com/7661533/32472762-c864a44e-c329-11e7-9d5c-734cf7a33138.png)

**Comment by mshukla1** [comment]
It is probably waiting or stuck in the indexing queue. We have been getting similar complains from users lately. 

I am advocating that we do not mark the job as complete until indexing is complete.

**Comment by jimdavis1** [comment]
It's been in the queue for like 18 hours.  It makes me think that something is wrong.  This is going to create a  problem for the workshop.

**Comment by mshukla1** [comment]
@nconrad 

Please check if the genome id exists in solr before enabling the view genome and related buttons. If the genome is not in solr yet, than show the icon grayed with a tooltip saying the genome is not indexed yet...or something like that.

**Comment by nconrad** [comment]
I'm hoping a message on the genome page will suffice instead.  That would also the cover the case where somebody goes directly to the page anyway.  The message I was thinking is:

"Genome <genome_id> was not found.  This could be because it is currently being indexed in the PATRIC database, it does not exist, or you do not have read privileges."

**Comment by hyoo** [comment]
confirmed
