### ISSUE TITLE
Reseting annotation page prevents autoload of taxon id when name is entered

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1793]
Several participants of the workshop have reported this.  After they submit their first annotation job, they hit the reset button and start to put in the information.  If they try and enter the name of the organism, the taxon ID will not autoload.  They get stuck here, and have to go away from the page and then come back to it.

Its true that if they know the taxon id, they can enter that and the name will load, but this appears to be a bug that I myself have experienced.

**Comment by dawenx** [comment]
i'm able to reproduce the issue, working on a fix.

**Comment by dawenx** [comment]
@ARWattam just a walk-around while we are working on a fix: after clicking on reset, choose a different taxon name (it will populate taxon id), then choose the original taxon name, this time, the taxon id will be populated.

**Comment by dawenx** [comment]
i worked on it a few weeks ago when this issue was opened, but i could not resolve it... when i tried to give it another shot today, i found the reported problem is not there any more. after looking into it, i think this was resolved by my recent fix on issue #1807.
@ARWattam can you double check on production? thanks!
