### ISSUE TITLE
Links to AMR data from NIAID Antimicrobial Resistance Sequencing Projects page all broken

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#184]
Every single link gives me a bad gateway page:
![screen shot 2015-05-12 at 10 47 55 am](https://cloud.githubusercontent.com/assets/11475316/7590047/69bb5cd8-f894-11e4-88fc-ea95268c92cf.png)

**Comment by rkenyon** [comment]
I'll fix them.

Ron Kenyon
PATRIC Project Manager, patricbrc.org
Project Management Director
Virginia Bioinformatics Institute, Virginia Tech
Ph: 540-231-7470

**Comment by rwill1** [comment]
The issue is that on http://enews.patricbrc.org/niaid-antimicrobial-resistance-sequencing-projects/ the Genome List links point to dev.patricbrc.org  (probably because we were working on the content before the release happened and all the genomes weren't release yet?)  and dev.patricbrc.org doesn't exist anymore.  Since Chunhong was instrumental in creating this page, and especially the link formatting, I suggest that she make the correction.

In addition, we need to add the 4 NIAID AMR data sets that got added in the Feb/Mar release.   They are all TB-ARC data sets (I am leaving out the 2 non-NIAID data sets).  They are (title string)
TB-ARC - KRITH
TB-ARC - KRITH 2
TB-ARC - MRC SA
TB-ARC - M.bovis

**Comment by rwill1** [comment]
Chunhong, were you going to add the 4 new NIAID AMR data sets (see above comment) to the page also?

**Comment by mshukla1** [comment]
I see that TB-ARC datasets are not added yet. Chunhong, please close the ticket when you do.

**Comment by maovt** [comment]
It's fixed. I'll add the new NIAID AMR data sets for the June release when they're ready.
