### ISSUE TITLE
patric.vbi.vt.edu no longer working

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#188]
This was the PATRIC 1 URL.  We used to have a redirect from here.  Maybe we don't need it anymore and don't care.

**Comment by rwill1** [comment]
The main reason to keep it alive is that it costs us little and there are pubs that point to it.

**Comment by hyoo** [comment]
DNS still pointing to our cluster (morgan-head-3.bioinformatics.vt.edu). So, if we want, we can configure the nginx to accept this domain. This cost little. However, I would prefer this domain redirects to the patricbrc.org, so that we don't have to duplicate all the detail configures and maintain it going forward.

nslookup patric.vbi.vt.edu
Server:		172.31.248.34
Address:	172.31.248.34#53

patric.vbi.vt.edu	canonical name = morgan-head-3.bioinformatics.vt.edu.
Name:	morgan-head-3.bioinformatics.vt.edu
Address: 128.173.97.11

**Comment by rwill1** [comment]
This sounds like a fine solution to me.   I vote that along with this we remove the "incumbent BRCs" pages (which is what the old version of the URL pointed to).   This also kills the problem w/ a possible other place that had the current / soon to be old help email address.  The only place that points to Incumbent pages is nmpdr.org and I will send an email to Bob to fix that.   Let me know if you want me to put the 2nd half of this into a separate issue.  (sorry bad behavior on my part linking things together so that nothing can ever be finished :-)!)

**Comment by mshukla1** [comment]
who owns this? Passing it to Dustin.

**Comment by dmachi** [comment]
I will get this deployed tomorrow

**Comment by rwill1** [comment]
Status - incumbent BRC pages were removed.   Bob changed NMPDR help pointer.  

What remains to be done is make patric.vbi.vt.edu redirect to patricbrc.org.

And I'm adding to this that we need to make patricbrc.vbi.vt.edu redirect to patricbrc.org  also (currently pointing to stahl I'm guessing based on output, although I didn't research it thoroughly) Ron can explain the political reason for this - but also we supported it for most of PATRIC2 and it got busted when we moved to the cluster.

**Comment by dmachi** [comment]
I've put the dns request in to change patricbrc.vbi.vt.edu to a CNAME to morgan-head-3.  It is currently a cname for stahl.  Once the DNS change goes into effect, the proxies have already be configured to redirect patricbrc.vbi.vt.edu/* to https://www.patricbrc.org/*

**Comment by dmachi** [comment]
CCF indicated that the dns request to CNS has been put through and should go into effect Thursday.

**Comment by dmachi** [comment]
Fixed.
