### ISSUE TITLE
User requests ability to download all correlated genes per genome

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1889]
Came from JIRA 1344 ticket
User would like to  download all "correlated genes" data of a particular genome from PATRIC

**Comment by dawenx** [comment]
I don't know what does it mean by "correlated genes per genome" and where should we put the download... @hyoo can you help me understand it or suggest a 'better' person to work on it?

**Comment by hyoo** [comment]
We have a correlated gene page in feature level. The correlated genes refer to genes that are likely up/down regulated with the given gene. This is calculated with transcriptomcis data in solr.

This page triggers a solr query to calculate correlated genes per feature. Currently we don't have a functionality to generate all the correlated genes per genome, since the correlation is calculated on the fly and one genome would have ~5000 genes.

@ARWattam do you have the genome id that user wants to download? Maybe we can make a script to query feature by feature with the given genome id.

**Comment by hyoo** [comment]
For E.coli, we have 7 genomes that can calculate correlation.
511145.12,386585.9,155864.8,199310.4,405955.13,362663.9,364106.8

Genome ID	Genome Name
"155864.8"	"Escherichia coli O157:H7 str. EDL933"
"199310.4"	"Escherichia coli CFT073"
"362663.9"	"Escherichia coli 536"
"364106.8"	"Escherichia coli UTI89"
"386585.9"	"Escherichia coli O157:H7 str. Sakai"
"405955.13"	"Escherichia coli APEC O1"
"511145.12"	"Escherichia coli str. K-12 substr. MG1655"

**Comment by hyoo** [comment]
We sent the data requested and this jira ticket is closed.
