### ISSUE TITLE
Enable zooming on Circular Genome Viewer

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#1896]
Seems like the only way to zoom now is to resize the browser window.

https://patricbrc.org/view/Genome/158879.11#view_tab=circular

**Comment by mshukla1** [comment]
The circular viewer is designed to give an overview of the entire genome, and generate a figure that can be placed in publication/presentation etc. Hence, it was not meant to have the level of interactivity you would have in genome browser. 

So, zoom in / out here means making the circular image bigger or smaller, without changes its content. 

Since, users can download the image as svg and zoom in or out without loosing clarity of the image< i think we have this covered. 

Closing the ticket.
