### ISSUE TITLE
BLAST DB update cycle is not clear

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1916]
In following blastn search, which is a gene against all of klebsiella,  the gene of interest does not find itself.

>fig|573.12458.peg.6128|B8O09_30180|   Class D beta-lactamase (EC 3.5.2.6) => OXA-48 family, some variants carbapenem-hydrolyzing   [Klebsiella pneumoniae strain KPN1482 | 573.12458]
atgcgtgtattagccttatcggctgtgtttttggtggcatcgattatcggaatgcctgcg
gtagcaaaggaatggcaagaaaacaaaagttggaatgctcactttactgaacataaatca
cagggcgtagttgtgctctggaatgagaataagcagcaaggatttaccaataatcttaaa
cgggcgaaccaagcatttttacccgcatctacctttaaaattcccaatagcttgatcgcc
ctcgatttgggcgtggttaaggatgaacaccaagtctttaagtgggatggacagacgcgc
gatatcgccacttggaatcgcgatcataatctaatcaccgcgatgaaatattcagttgtg
cctgtttatcaagaatttgcccgccaaattggcgaggcacgtatgagcaagatgctacat
gctttcgattatggtaatgaggacatttcgggcaatgtagacagtttctggctcgacggt
ggtattcgaatttcggccacggagcaaatcagctttttaagaaagctgtatcacaataag
ttacacgtatcggagcgcagccagcgtattgtcaaacaagccatgctgaccgaagccaat
ggtgactatattattcgggctaaaactggatactcgactagaatcgaacctaagattggc
tggtgggtcggttgggttgaacttgatgataatgtgtggttttttgcgatgaatatggat
atgcccacatcggatggtttagggctgcgccaagccatcacaaaagaagtgctcaaacag
gaaaaaattattccctag

![image](https://user-images.githubusercontent.com/7661533/37462333-8bd1ce2a-281f-11e8-9b07-167f5b2de5bf.png)

![image](https://user-images.githubusercontent.com/7661533/37462309-7e702498-281f-11e8-99d4-11f6befe1dcd.png)

**Comment by mshukla1** [comment]
It could have been due to the missing blast databases at the time. I ran the query again and was able to find self hit. 

I also verified that we have blast databases in place for all public genomes at this time. 

-Maulik

**Comment by rkenyon** [comment]
Jim triage comment: Highest.  Maulik closed the issue but it still is not fixed.   There are two issues. 

1.  any higher level taxonomy based search (order, class phylum) are either disabled or broken. 

2. As far as I can tell there appears to be no clear update cycle for these blast NRs, otherwise I would not have encountered the problem of a gene not existing in an NR in the first place. Not having standard update processes in place is a huge and pervasive problem through out the resource.

**Comment by hyoo** [comment]
Regarding #2, should we have a data-release version? like 2018.07 indicating 2018 July release? There are some time delay between the download files are updated/blast database build and genomes are indexed on solr.

**Comment by mshukla1** [comment]
The current order of operation is, 
1. add genomes to the database in batch mode
2. After all genomes are added for a release, create download files for FTP
3 After all download files are created, create blast databases 

Because 1 happens in real time and 2 and 3 happen asynchronously, there is time in between where genome is visible in the BLAST service, but blast database is not ready yet. 

To address this, I have tightened up the release process, so that 1,2 and 3 are executed sequentially, without any time lag.
