### ISSUE TITLE
ftp is still broken

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1926]
Are you guys ever going to fix the ftp so that the the legacy paths still work?  If not, you should at least post up a file of old_path -> new_path  for files that existed prior to the change.  It is sort of maddening that this happened with out public notice.

**Comment by mshukla1** [comment]
I will work on it this morning. 

-M

**Comment by mshukla1** [comment]
Is there anything specific you were looking for?

**Comment by jimdavis1** [comment]
We are **REQUIRED** to maintain the two FTP links to the AMR data that we published in previous papers.  This means that these links must remain active (I don't care if they redirect).

ftp://ftp.patricbrc.org/BRC_Mirrors/AMR/  and
ftp.patricbrc.org/patric2/current_release/RELEASE_NOTES/PATRIC_genomes_AMR.txt

**Comment by rkenyon** [comment]
Jim issue triage comment: Highest level problem.  We have published FTP links in previous papers that must be maintained and kept up to date (check out: https://www.nature.com/articles/srep27930).  

In my view this is the worst kind of problem because it erodes user trust.  Furthermore, we are staking our reputations on the reliability of PATRIC, and this is a case where that is not happening.

**Comment by mshukla1** [comment]
I have recreated links mentioned in the paper. 

ftp://ftp.patricbrc.org/BRC_Mirrors/AMR/

ftp://ftp.patricbrc.org/patric2/current_release/RELEASE_NOTES/PATRIC_genomes_AMR.txt

ftp://ftp.patricbrc.org/patric2/current_release/AMR_genome_sets/

ftp://ftp.patricbrc.org/patric2/patric3/genomes

Publication includes few links with http urls, i.e. http://ftp.patricbrc.org/, which are not working. 
We need to set up a redirect/alias from  http://ftp.patricbrc.org/ ro ftp://ftp.patricbrc.org/.

**Comment by aswarren** [comment]
ftp://ftp.patricbrc.org/patric2/patric3/genomes/9606.33

Doesn't seem to work
