### ISSUE TITLE
Comparative genome analysis job not viewable, although says that it completed and gives me an annotation...sort of.

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#1973]
I submitted a comprehensive genome analysis (job ID: 7e428dfb-7268-4935-9d14-3c86b6d7bd23) that I can see is complete, but when I try and click on it I get a workspace error and I can't see it.  So I can see that the assembly and annotation associated with it are complete (at least I'm assuming that its with that job as they are consecutive, but there is no obvious id linking them...users might not understand that), and when I click on the annotation (job ID a7df286f-a5a8-426e-8a5e-840ac24c2cc1), and then the Genome Report.html,  I get binning results and not what I was expecting.  Is this normal?

**Comment by olsonanl** [comment]
This job was a victim of the AWE problem that showed failed jobs as being successfully completed. The fixes to the app service https://github.com/olsonanl/app_service/commit/8f758c5d0cca5186e037b8803a93260f71ae8f1e result in the job properly showing as failed.

It failed due to the too-many-ideograms problem when creating the Circos plot.

By clicking into the annotation job you are seeing the report that is generated by the annotation service for a genome that includes only information about that genome (originally intended for use with the binning service).
