### ISSUE TITLE
some genomes are missing contig sequences

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1987]
I am doing a blastn against a genome group.  I am in the workspace "Salmonella_FDA"
![image](https://user-images.githubusercontent.com/7661533/39891054-40c7f5e8-5462-11e8-89fe-7dbb0096992f.png)

I am blasting the sequence: 
CCGCCTGGTTGACGC
Against the genome group "CIPR"

![image](https://user-images.githubusercontent.com/7661533/39891115-692a9dc4-5462-11e8-868c-3369a0d5dac9.png)

![image](https://user-images.githubusercontent.com/7661533/39891107-65ee54a2-5462-11e8-9595-a8bef62279eb.png)

I know the genome exists:
![image](https://user-images.githubusercontent.com/7661533/39891084-4fa9b6c8-5462-11e8-9295-e0ca0f359089.png)

**Comment by olsonanl** [comment]
This failed because the written .fna file was zero length; that is because the database is reporting it as having no sequences.

The genome is in a strange state. On the front page:

<img width="177" alt="screen shot 2018-05-15 at 12 03 32 pm" src="https://user-images.githubusercontent.com/2152226/40072006-0db45046-5838-11e8-915b-e1663d29828a.png">

But at the sequences tab:

<img width="1019" alt="screen shot 2018-05-15 at 12 04 12 pm" src="https://user-images.githubusercontent.com/2152226/40072038-1cc2be56-5838-11e8-9237-6c8b91b28402.png">

And a data API query:

```
  DB<9> x $d->query("genome_sequence", ['eq', 'genome_id', '590.12792'], ['eq', 'sequence_type', 'contig'], ['select', 'description,genome_name,accession'])
  empty array
```

I have modified the code to more clearly flag this problem. @mshukla1 should look into the database problem.

New error message shown:

<img width="787" alt="screen shot 2018-05-15 at 12 14 04 pm" src="https://user-images.githubusercontent.com/2152226/40072530-c4ef49fe-5839-11e8-9734-be46dbeb25ef.png">

**Comment by rkenyon** [comment]
Jim triage comment: Highest level problem.  It has to do with the fact that some genomes in patric don't have contigs.  It looks like it is still an ongoing issue.

**Comment by mshukla1** [comment]
There were 208 Klebsiella genomes for which contig sequences were not loaded in the database, I suspect because of solr or data API server issues in December, just before the Christmas.  

I have loaded all missing contig sequences in the database. 

Harry has addressed it in the data API / solr indexer as well, so that we don't have such partially indexed genomes in solr in future.

**Comment by mshukla1** [comment]
...updating corresponding blast databases now.

**Comment by mshukla1** [comment]
Updated blast databases as well. Closing the ticket. 

Feel free to reopen if you still see any problems.
