### ISSUE TITLE
Disable Edit Type for folders in Workspace

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#1989]
My understanding is that this feature is not applicable for folders.

**Comment by nconrad** [comment]
I thought it would make more sense to disable the the button when the type can't be changed.  But, now I'm thinking it makes more sense to keep the message that currently pops up so that it's clear what can and can't not be changed

![image](https://user-images.githubusercontent.com/1194246/41440205-50a74610-6ff3-11e8-9fe8-e43728867ea5.png)
