### ISSUE TITLE
back button not working

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#1999]
1) go to patricbrc.org
2) navigate to data page or such
3) try back button

**Comment by olsonanl** [comment]
I'm not sure if this is related but in trying to use the back button starting from a genome list output of a search through to a genome, I end up with URLs of the form https://www.patricbrc.org/remote#view_tab=overview that do not do anything when I click on the tabs

**Comment by chris-c-thomas** [comment]
I noticed this as well when working on the homepage. Removing the search from the header caused it not to reappear when you went to other pages because the SPA doesn't seem to "fully load" the page content. It kept the modified p3header-new* template file (sans search bar) loaded instead of loading the original p3header template file (Even though it was set to show that view)

It felt like something was artificially restricting the app from ~~reloading~~ updating.

**Comment by olsonanl** [comment]
If we're going to do the SPA thing we really need to fix up all of these glitches. They make the site very frustrating to use.

**Comment by nconrad** [comment]
@chris-c-thomas do you want to take this one?  May need input from @dmachi or @hyoo.  I *think* this issue was introduced in the last update.

**Comment by chris-c-thomas** [comment]
@nconrad I'll look more in depth at it tomorrow morning but probably reach out to you or @dmachi if needed. I'm thinking it's purely Express related.

**Comment by nconrad** [comment]
Although other issues remain, the reported issue was fixed, so i'm closing this.
