### ISSUE TITLE
Need some work on Global Search results page in light of new IDs?

### ISSUE THREAD

**Issue by rwill1** [PATRIC3/patric3_website#2]
Global search for Rv2429
On the Global Search initial page the 1st feature says

alkyl hydroperoxide reductase subunit D | ahpD
Mycobacterium tuberculosis H37Rv
CDS | Rv2429 | Rv2429

Its icon is marked as RefSeq and there is no PATRIC ID displayed.

If you expand to the 55 Feature results, the initial feature name is
Alkylhydroperoxidase protein D and there is a PATRIC ID

This name is ALSO what is shown if you click on the initial feature on the initial Global Search landing page.

So there seems to be some issue w/ the way the Global Search landing page is representing that result?

**Comment by hyoo** [comment]
![image](https://cloud.githubusercontent.com/assets/1236467/25009758/688ee43e-202d-11e7-8107-a946b626e6eb.png)

![image](https://cloud.githubusercontent.com/assets/1236467/25009770/71780ea4-202d-11e7-9efa-b26114c5b0a4.png)

Original ticket was against JBoss, but I am showing the current result new UI.
Global search results looks same, but once you clicked the first result, it shows PATRIC ID because we map it to PATRIC features.
