### ISSUE TITLE
bogus collection date displayed in genome

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#2000]
In https://www.patricbrc.org/view/Genome/217090.3 we have:

Collection Date | NaN/NaN/NaN

**Comment by olsonanl** [comment]
Also: 

Length: undefinedbp, Chromosomes: 0, Plasmids: 0, Contigs: 0

**Comment by nconrad** [comment]
The first issue is due to lack of standardization on the collection dates https://github.com/PATRIC3/patric3_website/issues/1814 .

**Comment by mshukla1** [comment]
Collection date is stored as string in the database and should be treated as such. There are examples where collection date is given as a range, ie. 2004-2006, etc. We can't convert them to precise date, but don't want to exclude them either, hence, treated as string. 

Collection year is a clean version for faceting, YYYY, when possible. 

Bob, Regarding the genome stats, there are ~1500 genomes from the May release that did not get stats because rast2qc was not deployed when they were processed. I am going to add those missing stats Today. 

-Maulik

**Comment by nconrad** [comment]
Ok, I'll just print the string for collection date when it's not in timestamp format.

**Comment by mshukla1** [comment]
If it is straight forward, can you make the change Today, so it gets rolled up in the release? 

-Maulik

**Comment by hyoo** [comment]
![image](https://user-images.githubusercontent.com/1236467/41296703-1b25a116-6e23-11e8-94e5-b3d3ceceff74.png)

confirmed on production.
