### ISSUE TITLE
folder selection doesn't work

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#2029]
Any place I click on a teh folder icon to do a selection of a folder (e.g. picking a genome group folder) if I click into the folder I want and say OK, the selection comes back blank.

![screen shot 2018-07-12 at 2 13 11 pm](https://user-images.githubusercontent.com/2152226/42654316-d6c843a2-85dd-11e8-81ed-fd10e538bfcf.png)

**Comment by dawenx** [comment]
Bob: I tried it for a while and I do see it happened once, but I don't remember how I got there. Once I applied a small change on my local copy (in WorkspaceObjectSelector.js, this is related to #1978) and tried it, I don't see it any more. I'm not saying the problem is fixed and I suggest @nconrad to deploy his fix on WorkspaceObjectSelector.js. Two of us can test it more to see whether we still have this problem.

**Comment by nconrad** [comment]
@olsonanl would you mind verifying this is fixed?

**Comment by nconrad** [comment]
Actually, the groups folder selection still needs a couple changes, i'll push now.

**Comment by nconrad** [comment]
@olsonanl ok, latest updates are on alpha now, if you want to test.
