### ISSUE TITLE
Quickstart Video Appears Several Times Daily

### ISSUE THREAD

**Issue by Tinyman392** [PATRIC3/patric3_website#2048]
From ATCC workshop, multiple users are stating that the QuickStart video that appears when you first start using PATRIC is appearing several times a day on their Windows machines (it looks like windows 7) running Chrome, it may happen on other browsers as well.

**Comment by dmachi** [comment]
This will need some debugging on a windows machine to see what is happening.  We can remove the autoplay altogether if desired.  The QuickStart video remembers it has already been played by setting a value on browser local storage.  So if it is playing more than once, it is either failing to set that value (perhaps due to security somewhere) or it is getting cleared out.

**Comment by hyoo** [comment]
Check the browser configuration whether it has "clear cache/history when closing" configured. 
see https://k12parentportal.force.com/k12help/s/article/Set-Browser-to-Clear-Cache-When-Closing 
for setup.

**Comment by hyoo** [comment]
sorry, wrong click.

**Comment by dmachi** [comment]
I’m not too concerned if this happens after clearing cache, though  people can avoid it by not clearing the local storage when they clear cache as you pointed out.  I assumed, perhaps incorrectly, that this error is happening without clearing cache.

**Comment by chris-c-thomas** [comment]
Is this still an issue? I don't experience it in day to day things but if I load incognito or with cleared cached I do, which is to be expected.

**Comment by Tinyman392** [comment]
I haven't seen it lately.

**Comment by chris-c-thomas** [comment]
I'm going to assume browser updates have caused it to behave the way we intended or something similar. Closing.
