### ISSUE TITLE
Important issue: Minhash mash files are out of date

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2080]
The following genome, made public in January does not find itself in the similar genome finder.

![image](https://user-images.githubusercontent.com/7661533/44220552-8d94fe00-a144-11e8-98ed-9e95d6b1699c.png)

**Comment by mshukla1** [comment]
Bob, what is the current process for generating the minhash sketches for the public genomes? Is it automated or do you generate them manually after every release? 

If latter, I can make it part of the same update process as generating download files and BLAST databases, so that you have one less thing to worry about. This is not automated either, but I have been thinking about it as part of consolidating the whole data update cycle. 

-Maulik

**Comment by olsonanl** [comment]
It is not automated but mostly scripted.

I need to get some of this stuff checked in.

The quick story is

minhash-build-sketches -p 12  /vol/patric3/downloads/genomes /disks/patric-common/data/minhash/sketches
mkdir /disks/patric-common/data/minhash/combined.2018-0806
minhash-create-combined-sketches /disks/patric-common/data/minhash/sketches /disks/patric-common/data/minhash/combined.2018-0806

Visually check, and then swing the symlink /disks/patric-common/data/minhash/combined to point at the new directory. This happens on gum.mcs.anl.gov<http://gum.mcs.anl.gov>.

—bob

On Aug 16, 2018, at 4:09 PM, Maulik Shukla <notifications@github.com<mailto:notifications@github.com>> wrote:


Bob, what is the current process for generating the minhash sketches for the public genomes? Is it automated or do you generate them manually after every release?

If latter, I can make it part of the same update process as generating download files and BLAST databases, so that you have one less thing to worry about. This is not automated either, but I have been thinking about it as part of consolidating the whole data update cycle.

-Maulik
