### ISSUE TITLE
add to group: colon in group name doesn't work

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#210]
Adding genomes to a group, when use colon ":" in the group name and save, I get the notification that genomes were added to the workspace, however, the group never appear in the workspace. It looks like 
group creation fails without giving any error message to the user.

**Comment by olsonanl** [comment]
This is apparently a workspace issue:

JSONRPC error data:_ERROR_Object name file:name contains forbidden characters!_ERROR_

Chris - why is the workspace disallowing any characters from object names?

**Comment by olsonanl** [comment]
Additionally if we cannot fix that - what is the set of characters that is not allowed? We need to be able to trap those in the UI to give reasonable error messages.

**Comment by cshenry** [comment]
I do not want to allow characters that would break things if the workspace was cloned to your filesystem. ":" is not allowed in filenames on my filesystem at least. I think this is a reasonable position to take. 

Right now, I think the name validation is something like this:
if ($input =~ m/[:\/]/) {
		$self->_error("Object name ".$input." contains forbidden characters!");
	}

So literally... you can use ANYTHING but ":" and "/". Is that okay?

**Comment by olsonanl** [comment]
I think windows is the only case where this is an issue; mac and linux are both fine. 

mcswl174:~ olson$ date > foo:bar
mcswl174:~ olson$ ls -l foo.bar
-rw-r--r--  1 olson  staff  29 Jun  3 15:11 foo:bar

Do we support cloning the workspace to the filesystem?

Harry / Maulik - I suspect the correct solution here is to not name genome group files with the name of the group, but rather include the name of the group inside the data file; that way any bizarro quoted characters may be used in the group names. The filename can be a safely quoted version of the group name.

**Comment by olsonanl** [comment]
Chris comments that in Finder in the mac you can't do it either and I see that he is right. I'd make the same argument to Apple but I'll save my breath :-)

**Comment by olsonanl** [comment]
@cshenry  do you know if workspace is clean with respect to full UTF 8 chars e.g. ∆

**Comment by cshenry** [comment]
We don't do any sort of escaping of workspace or object names. So if you try and use a character that can't be in a file name, it won't work....

I got to wonder why anyone would want to name an object something that you can't even type on a keyboard... It renders it very hard to use...

**Comment by olsonanl** [comment]
We had user-submitted job failures due to the delta (which is easy to type, Option J on a mac). It can be in a filename. I tested this with RAST and it works fine:

[cid:1790452A-AFBC-4680-9A89-15C185D07F5A@mcs.anl.gov]

gally2:~ olson$ cd √θθθ
gally2:√θθθ olson$ pwd
/Users/olson/√θθθ
gally2:√θθθ olson$ ls -l
total 752
-rw-r--r--@ 1 olson  staff  381805 May 12 11:11 √θθθ.gb
gally2:√θθθ olson$ head √θθθ.gb
LOCUS       NC_008512             159662 bp    DNA     circular BCT 16-MAR-2010
DEFINITION  Candidatus Carsonella ruddii PV, complete genome.
ACCESSION   NC_008512
VERSION     NC_008512.1  GI:116334902
DBLINK      Project: 17977
KEYWORDS    .
SOURCE      Candidatus Carsonella ruddii PV
  ORGANISM  Candidatus Carsonella ruddii PV
            Bacteria; Proteobacteria; Gammaproteobacteria; Candidatus
            Carsonella.




On Aug 19, 2015, at 4:09 PM, cshenry <notifications@github.com<mailto:notifications@github.com>> wrote:

We don't do any sort of escaping of workspace or object names. So if you try and use a character that can't be in a file name, it won't work....

I got to wonder why anyone would want to name an object something that you can't even type on a keyboard... It renders it very hard to use...

**Comment by olsonanl** [comment]
Picture didn't come through:
![screen shot 2015-08-20 at 10 27 39 am](https://cloud.githubusercontent.com/assets/2152226/9387439/1e4ad446-4726-11e5-9c2d-aa2f0a3fcc65.png)

**Comment by cshenry** [comment]
OK. I have no idea why this would fail in the workspace. It will take some time to debug. Let�s make it an issue. I�m not personally going to have time to address this for a few weeks� just too much going on right now.

**Comment by hyoo** [comment]
the original problem, adding : in the group name is resolved by blocking from UI. 
I am closing this ticket.
