### ISSUE TITLE
Diff expression job is not run with Rockhopper

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#2109]
I ran an RNA-seq job this morning with the Rockhopper option. 
RNA-seq part ran fine and created gene matrix (gmx) file. 
However, differential expression job results were not part of the output. 

Please make sure diff exp job is ran as part of rna-seq when Rockhopper is selected. 

-Maulik

**Comment by aswarren** [comment]
When initially developing the execution of diff exp app we hadn't perfected the running of other apps from within apps yet. It was suggested we "simulate" the running of another app by invoking the diff exp back end script and creating a "fake" job object. 
Now that we have gotten the running apps further developed, it should be a dev task to rip the diff exp running back out of prok_tuxedo and invoke the p3-diffexp from the top level perl wrapper script so that in both cases....rockhopper & tuxedo the same, regular diffexp will be called.
As it stands right now, rockhopper is still in the old mode of having to invoke diffexp using the gmx file afterward.

**Comment by mshukla1** [comment]
We removed RockHopper Recipe from the submission form, so I guess this is no longer an issue.
