### ISSUE TITLE
mauve giving odd results

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#2133]
I am comparing these jobs:

```
{
  "genome_ids": [
    "1262932.43",
    "1262932.44"
  ],
  "output_file": "comp.2018-10-08-13-29-38.bin2",
  "output_path": "/olson@patricbrc.org/PATRIC-QA/applications/App-MetagenomeBinning",
  "recipe": "progressiveMauve"
}
```

The display I get is this:

![image](https://user-images.githubusercontent.com/2152226/46629876-f6c33d00-cb07-11e8-9410-d2fb5343694e.png)

But the genomes are the same length:

![image](https://user-images.githubusercontent.com/2152226/46629890-fe82e180-cb07-11e8-8087-4feacb9fd0da.png)

Any idea what's happening?

**Comment by nconrad** [comment]
This is fixed with the fasta download fix deployed on 4/25/2019.

![image](https://user-images.githubusercontent.com/1194246/57327256-0faec380-70d4-11e9-9960-b0912149075e.png)

I'm noticing that the viz is struggling quite a bit with the 1747 x 2 = 3,494 contig markers when zoomed out, which is a little surprising.  I'll see if that can be improved.  I've added that issue to https://github.com/PATRIC3/patric3_website/issues/2202 for now.
