### ISSUE TITLE
How many files are in my workspace directory??

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2150]
This issue keeps getting closed, and I'm going to keep reopening it.   I need to know how many items are in a workspace directory.

Here is an example of how box deals with the problem.  There is precedence for this, and it is needed. 

![image](https://user-images.githubusercontent.com/7661533/48135279-10b88280-e262-11e8-852e-b8d7350c7bde.png)

**Comment by nconrad** [comment]
@jimdavis1 It's not closed.  It's still open here: https://github.com/PATRIC3/patric3_website/issues/1839.  It has been low priority since you can select all the the files to get the count.  However, I'll make it higher priority.

Note: Giving counts the Box way isn't possible without some workspace service updates.
