### ISSUE TITLE
can't select contig file from job result folder 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#2158]
I am trying to select contig file generated by one of my previous assembly jobs to use as inout for the annotation service. 

I go to annotation submission 
click on folder icon next to select contigs
browse to the directory that contains my assembly job results

However, I cant see the job result directory which contains contig file. 

We have a checkbox which says "show all files and folders"....however, it doesn't show hidden job result folders. 

This needs to be fixed ASAP. 

-Maulik

<img width="520" alt="screen shot 2018-12-04 at 8 09 34 am" src="https://user-images.githubusercontent.com/1236463/49447675-be08b280-f79c-11e8-9082-98f768fe47a4.png">

**Comment by nconrad** [comment]
This must have been broken for awhile!  So there's a fix in.   The solution isn't ideal without some heavier refactoring.  

The fix is to tie both the workspace browser "show hidden" and the object selector "show all" button to the same state... which almost results in reasonable behavior, *except* clicking the "show all" in one dialog will not update another dialog that has already been open before (on the same page).

1) Ideally, IMO, the showHiddenFiles state would persist for the regular workspace browser, separate from the object selector.  This would be similar to Mac OS.  However, the object selectors in apps (the folder button) are closely tied to the workspace browser code and state for fetching the object lists.

2) Kind of unrelated, but not good:  all of the object selectors are never tore down properly.  The selectors leave garbage in the DOM and probably memory too.
