### ISSUE TITLE
DLP: Transcriptomics landing page

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2163]
Here are some issues I am having with the transcriptomic data set landing page:
How many transcriptomic data sets are there?
How to I get to all transcriptomic data sets from this page?
How do I get to the transcriptomic data sets for other organisms (besides the top 5) from this page?

The rationale for the "featured experiments" is not immediately obvious unless you are going to allow people to browse all experiments.  Maybe we need "more" buttons at the ends of these lists?

![image](https://user-images.githubusercontent.com/7661533/49687198-58326880-fac5-11e8-9a66-06b5b67d8a6a.png)

**Comment by mshukla1** [comment]
All of the data landing pages are now outdated or obsolete. 

I am in favor of revamping them to make them more relevant to the current data and content, or getting rid of them. 

-Maulik

**Comment by rkenyon** [comment]
We could check Google Analytics on those pages and see if they are getting any significant traffic.  If not, maybe we can retire them.

Ron

**Comment by chris-c-thomas** [comment]
Would it make sense to revamp the landing pages within Patric Docs?

**Comment by rkenyon** [comment]
The information could be put there.  I suppose the links back into the website could as well, but the dynamic content is probably more challenging.

Ron

**Comment by mshukla1** [comment]
I am leaning toward having easy to maintain user guides for data types, instead of having
obsolete data landing pages.


We have major data types currently listed here.
https://docs.patricbrc.org//user_guides/data.html

This list is limited because those are the Only data types we currently have
available from the Top Nav, which is again because those are the only ones for
which we have DLPs.

With document site, we can expand the list to include more relevant data types, i.e.
subsystems, PPI, etc.

Them, for each of the data types, we can provide link to a dedicated data type user guide,
Which can describe

- what is that data type
- source of data in PATRIC
- how data is processed / curated
- what services we have for the data type
- what analysis / viz tools we have
- relevant CLI functions for downloading the data
- link to FTP

We do not need to repeat the content of the tutorial or user guides for services/tools etc,
Just need to provide context and pointer.

I think this will be much more manageable that the current DLPs.

Thoughts?

-Maulik








On Feb 21, 2019, at 10:22 AM, rkenyon <notifications@github.com<mailto:notifications@github.com>> wrote:

The information could be put there. I suppose the links back into the website could as well, but the dynamic content is probably more challenging.

Ron

**Comment by mshukla1** [comment]
Just to add, I like them not to have any dynamic content, which hard to maintain and update with continuous data releases.

**Comment by chris-c-thomas** [comment]
I think maintaining through the docs site then is definitely the easiest approach. Update through GitHub whenever needed and commit the changes, then reflected automatically once it rebuilds.

**Comment by rkenyon** [comment]
I agree with Maulik's suggestion too.  Let's move forward that way.  Chris do you want to take the lead?

**Comment by chris-c-thomas** [comment]
Yes, I'll begin to convert and we can update the content with current information.

**Comment by mshukla1** [comment]
I have added links to all bacterial and host response datasets and services and tools.
