### ISSUE TITLE
Heatmap reported to not work on Chrome Version 71.0.3578.98

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2168]
I have Chrome Version 71.0.3578.98 (Official Build) (64-bit) for Windows. 
This problem also occurs on the Mac, where I have version 70.0.3538.110. 
The heatmap feature of the protein family sorter is unusable. In modern 
Chrome, the only way to enable Adobe flash is to click on the little 
message that shows up. Since a custom display appears instead, the little 
message does not show up, there is no way to click on it, and instead I am 
directed to a help page with completely obsolete information. I have 
attached a screen shot of the little message that appears on normal flash 
web pages.

**Comment by hyoo** [comment]
need to update 
https://docs.patricbrc.org/tutorial/enabling_flash/enabling_flash.html

**Comment by chris-c-thomas** [comment]
I will update the tutorial.

@ARWattam can you show me the screenshot of the little message? I don't think it uploaded to GH, or I'm missing it?

**Comment by chris-c-thomas** [comment]
Also, will write instructions for Firefox, Safari, Edge, etc as needed.

**Comment by chris-c-thomas** [comment]
@ARWattam - I'm going to assume this is no longer an issue for the user and close the ticket since it's been a month. If they are still experiencing the issue we can work one on one to enable their Flash Player.

I've just rewritten an updated version of the Flash Player tutorial that should be easier to follow. It covers modern versions of Chrome, Firefox, Safari and Edge.

https://github.com/PATRIC3/p3_docs/pull/83 is the update. It will go live on the docs website when it auto updates soon.
