### ISSUE TITLE
metadata filters don't make sense

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2178]
Marcus and I are looking at the specialty genes for Klebsiella and we want to filter for the K-mer-based AMR calls.  When you click the filter button, you get things that don't make any sense.  See image below 

https://www.patricbrc.org/view/Taxonomy/573#view_tab=specialtyGenes

![image](https://user-images.githubusercontent.com/7661533/51338419-5b6b2d80-1a4f-11e9-9423-12bc0b8dcb1f.png)

**Comment by mshukla1** [comment]
The progressive filters / facets correspond to whatever columns/attributes available in a given table displayed on that page. Hence, they are not always about genome metadata, if that is what you were expecting. 

You could use the filter instead of keyword search to find all amr genes by k-mer based evidence 
as below. 

<img width="962" alt="screen shot 2019-01-18 at 3 38 13 pm" src="https://user-images.githubusercontent.com/1236463/51414192-20442980-1b37-11e9-93bd-bd2c3e2ab2f7.png">
