### ISSUE TITLE
WHAT VERSION OF MLST ARE WE USING??

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#2213]
Marcus and I have a list of 1330 staph genomes, less than 100 have an mlst type based on patric.  
What version of MLST are we using?  Can we defend this?  Shouldn't staph be one that we support?  

It is time to have a conversation about moving the MLST typing pipeline into rasttk. 

[test.staph.txt](https://github.com/PATRIC3/patric3_website/files/2890853/test.staph.txt)

**Comment by olsonanl** [comment]
Did you see the response on the other ticket about this?

**Comment by mshukla1** [comment]
Jim,

You asked the same question a week ago and Bob responded to the ticket saying.

“It is a modified-to-run-here version of whatever we inherited from the person who is
no longer with the project. Code at https://github.com/patric3/p3_mlst
Database used is /disks/patric-common/data/mlstdb-2015-1123”

Nothing has changed since then.

Are you asking the same question again with all caps this time and looking for different answer?

As far as I know MLST databases don’t go by version numbers, they are updated frequently and
Referred to by the date when you downloaded or accessed them.

It will take a while to get our head around the code and update the databases.

I am willing to do it, but it may take some time given I already have other things
on my plate right now…such as getting the AMR metadata, AMR genomes, cryptic genomes,
Italian genomes integrated and have metagenomics databases ready, all of which are high
priority.

I will spend sometime in it this weekend and see if I can update the databases with the existing scripts.

Bob can correct me if I am wrong, but I believe it is MLST already integrated in RASTtk.

Unless someone is willing to rewrite the code for integrating it in RASTtk and/or maintain M LST databases,
you won’t get any different results by integrating current code and current database.

We do support Staph as part of MLST and there are >5000 staph genomes currently on the database
With MLST assignments. Perhaps the number would be higher if we had the latest MLST database...
How much, I don’t know.

-Maulik



On Feb 21, 2019, at 1:23 PM, jimdavis1 <notifications@github.com<mailto:notifications@github.com>> wrote:


Marcus and I have a list of 1330 staph genomes, less than 100 have an mlst type based on patric.
What version of MLST are we using? Can we defend this? Shouldn't staph be one that we support?

It is time to have a conversation about moving the MLST typing pipeline into rasttk.

test.staph.txt<https://github.com/PATRIC3/patric3_website/files/2890853/test.staph.txt>

**Comment by mshukla1** [comment]
All MLST databases have been updated in February, 2019 and deployed in the annotation pipeline.

MLST assignments for all public genomes have also been updated.
