### ISSUE TITLE
Make CLI dmg more accessible

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#2227]
Below is the original request from Jim and my response to it. 

URL: https://www.patricbrc.org/app/IDMapper
User ID: jdassembly
Email: jjdavis.phd+assembly@gmail.com

It would be really nice if you could download the PATRIC DMG from one of 
the dropdown menus on the home page.

**Comment by mshukla1** [comment]
I am in favor of providing more direct / visible link to CLI documentation from the top menu.  

However, in my view, github is a better place for providing latest downloadable version of CLI and providing version history/change log etc. It is standard for making software available to public. 

Besides, there are multiple flavors of the CLI package for different platforms, i.e. .dmg, deb, exe, source code, etc.  If we provide only dmg, that won't meet needs of all users. 

I defer it to Bob. 

 

-Maulik

**Comment by olsonanl** [comment]
I don't have a strong opinion. If we can add a useful page to the website that we can trivially update with new versions, that'd be best. @hyoo Harry ?

**Comment by hyoo** [comment]
I interpret the user request as "It is difficult to find the link to the installable file".


From the CLI button on the homepage, the link goes to https://docs.patricbrc.org/cli_tutorial/

and usually people would expect to see a big download button, like below,

[cid:DC4124CC-DFEF-4631-A7D1-D65F9636FBD4@hsd1.il.comcast.net.]


Our link to the release page (or download page) is a text.


[cid:8E4CA142-494C-49CF-888D-C40763A1CFCB@hsd1.il.comcast.net.]


which is not obvious.

I suggest to add a big download button below the "The release are available at the PATRIC3 github site" paragraph.

I don't think a direct link would solve the problem, because, our CLI installer would require some instruction, such as the the authentication workaround. So, I would put another big box, that links to the instruction page. Yes, those are redundant, but are important to pop out, i think.

Harry


On Apr 1, 2019, at 4:47 PM, olsonanl <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't have a strong opinion. If we can add a useful page to the website that we can trivially update with new versions, that'd be best. @hyoo<https://github.com/hyoo> Harry ?

**Comment by chris-c-thomas** [comment]
I think @hyoo's approach makes sense given that's how many users are used to downloading programs. A download button for the most recent release as well as "other platforms" or "previous releases" type links for that?

A direct download for the most recent release in the header menu might be worthwhile or at least link it to this spot with the big download button? I see the redundancy as beneficial.

Side note: @olsonanl the docs info says Windows OS in the works but the recent releases shows a .exe  so should that be changed? 

**Edit:** Adding this screenshot for reference from a popular download page. Big download button link. Other platforms link. Release notes link.

<img width="1079" alt="Screen Shot 2019-04-01 at 7 19 21 PM" src="https://user-images.githubusercontent.com/22353987/55367547-3b2a0700-54b3-11e9-89e5-c279dcbea4fe.png">

**Comment by olsonanl** [comment]
This is a site design issue. I am going to close it; we can take it up if desired in the BV-BRC design discussions but there has never been any other request for this as far as I know.
