### ISSUE TITLE
Specialty gene link to Victors not responding

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#224]
For my private genome, on the specialty gene landing page
![screen shot 2015-06-04 at 4 13 11 pm](https://cloud.githubusercontent.com/assets/11475316/7993540/cba69bcc-0ad4-11e5-9113-5c2edbf88360.png)

I clicked on Victors and got this
![screen shot 2015-06-04 at 4 13 15 pm](https://cloud.githubusercontent.com/assets/11475316/7993546/d5797930-0ad4-11e5-8f45-3877a2439e9c.png)

**Comment by mshukla1** [comment]
Harry, I think the problem is that for all external links we are adding https:// in the beginning, which breaks the link. For example, the link below from the patric site doesn't work. 

https://www.phidias.us/victors/gene_detail.php?c_mc_victor_id=173

Change it to http and it works. 

http://www.phidias.us/victors/gene_detail.php?c_mc_victor_id=173

Please make the same change for all external links from the specialty gene table. 
The same goes for other external links on feature overview page and other places. 

-Maulik

**Comment by hyoo** [comment]
fixed and available on beta.
