### ISSUE TITLE
long tutorial titles

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/patric3_website#2240]
I'm wondering if the "at/in PATRIC" in the titles are needed?  

![image](https://user-images.githubusercontent.com/1194246/55908354-cf285c80-5b9e-11e9-950a-e29a6385345e.png)

**Comment by chris-c-thomas** [comment]
Easily removable if we want. I had actually removed a bunch from the patric header menu dropdown as it seemed redundant.

**Comment by mshukla1** [comment]
Chris,

Dropped from PATRIC header menu dropdown? Can you give an example, so I understand?



On Apr 10, 2019, at 2:49 PM, Chris Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


Easily removable if we want. I had actually removed a bunch from the patric header menu dropdown as it seemed redundant.

**Comment by chris-c-thomas** [comment]
<img width="177" alt="Screen Shot 2019-04-10 at 2 55 06 PM" src="https://user-images.githubusercontent.com/22353987/55909076-b325ba80-5ba0-11e9-8357-fe1636ef02d1.png">

<img width="154" alt="Screen Shot 2019-04-10 at 2 54 59 PM" src="https://user-images.githubusercontent.com/22353987/55909081-b7ea6e80-5ba0-11e9-863f-57e3ed4a0fe2.png">

An older version of the site had "at PATRIC" or "in PATRIC" in the dropdown for many of the selections. For example, I shortened 'PATRIC Privacy Policy' to 'Privacy Policy' since it's obvious most things are related to PATRIC.

**Comment by mshukla1** [comment]
Got it. Thanks.

Regarding the tutorials, I remember in early days we first started creating them as word/pdf docs that are hosted
On the website and can be printed and used by the participants in the workshop. So, in that case, it made sense to
Have “In PATRIC” in title.

However, I agree that it is redundant and can be removed on the doc site. Please confirm with Ron/Rebecca before
Making the change all across the board.

-M

On Apr 10, 2019, at 2:57 PM, Chris Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


[Screen Shot 2019-04-10 at 2 55 06 PM]<https://user-images.githubusercontent.com/22353987/55909076-b325ba80-5ba0-11e9-8357-fe1636ef02d1.png>

[Screen Shot 2019-04-10 at 2 54 59 PM]<https://user-images.githubusercontent.com/22353987/55909081-b7ea6e80-5ba0-11e9-863f-57e3ed4a0fe2.png>

An older version of the site had "at PATRIC" or "in PATRIC" in the dropdown. For example, I shortened 'PATRIC Privacy Policy' to 'Privacy Policy' since it's obvious most things are related to PATRIC.

**Comment by rkenyon** [comment]
I think they should be parallel in title structure as well, for example
Assemble a Genome
Annotation a Genome
Analyze Genome Quality
Perform Comprehensive Genome Analysis (this one is a bit awkward due to the title of the service)
Explore a Private Genome
BLAST Sequence(s)

etc.

**Comment by mshukla1** [comment]
@chris-c-thomas this is also related to what you are working on this week. So, you can address it at the same time.

**Comment by chris-c-thomas** [comment]
Tutorial titles have been cleaned up and are reflected in the navigation menus. If a title or page needs to be changed it can be done so on a case by case basis. Closing.
