### ISSUE TITLE
Job results: info link should take to the user guide for that service 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#2243]
I am looking at the RNA-seq job result folder. 

When I click on the "Info" button in the green bar, it takes me to PATRIC private workspace user guide below. 

https://docs.patricbrc.org/user_guides/workspaces/workspace.html

I think it will help if we replace this (or add another link) to theresult section of the user guide for that specific service.

**Comment by nconrad** [comment]
This is on prod.  It's not perfect because the top summary has to be loaded for the link to point to the user guide (among other reasons).... but it's probably good enough for now.

![60462776-d85e1e00-9c0f-11e9-8342-d47798f721d6-1](https://user-images.githubusercontent.com/1194246/60462904-312db680-9c10-11e9-8735-67feb2780231.png)
