### ISSUE TITLE
Popup window cannot be closed

### ISSUE THREAD

**Issue by AllanDickerman** [PATRIC3/patric3_website#2266]
When I clicked on "Edit Type" in the green bar for an Annotation job result in my workspace, a popup window popped up with the text below. The problem is there is no close button on the popup and I cannot use the page (it is modal).

Cannot Change Type
The selected items must be one of the following types: 
unspecified
contigs
nwk
reads
diffexp_input_data
diffexp_input_metadata.

However, your selection contained the type(s): 
job_result

**Comment by nconrad** [comment]
Hey @AllanDickerman.  I just wanted to check that there's at least a "X" button at the top right of the modal?  

![image](https://user-images.githubusercontent.com/1194246/56987476-2644a000-6b53-11e9-9ab2-7d65550bde80.png)

I agree there should probably be an "ok" button, primarily since we don't use click-outside-to-close on modals.
