### ISSUE TITLE
GenomeReport Problematic Roles Table has redundant column

### ISSUE THREAD

**Issue by AllanDickerman** [PATRIC3/patric3_website#2267]
The "Annotated count"  and "Feature link" convey the same information.
The second on has the link, but conveys the count as well.
We could save space by merging to one column ("Annotated Count")
with the count-link.

**Comment by bparrello** [comment]
The difficulty here is that it would be really hard to hit the link, since it's usually a single digit.  If we added the word "feature" to make the text bigger, then it would lose its similarity to the previous column for comparison purposes.  I am not sure what the best answer is, and would like feedback from multiple people.

**Comment by mshukla1** [comment]
Looks like the current solution is working and no specific actions needed here. closing the ticket.
