### ISSUE TITLE
Problem with clustering on Protein Family Sorter

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2340]
The following genomes produce an error when a user tries to cluster them on the Protein Family Sorter.  Maulik thinks it is timing out, but this shouldn't happen:
1392.242
1392.324
1392.379
1392.635
1392.642
1412842.4
1428.425
226900.8
260799.14
261594.21
281309.8
288681.15
347495.3
405535.8
412694.7
451709.7
486624.3
526970.3
526979.3
526985.3
527022.3
527028.3
527029.3
527032.3
572264.4
637380.6
86661.165

**Comment by mshukla1** [comment]
Neal, the problem is I think clustering request times out after two minutes of waiting for the results to return.

I think we should increase the timeout from 2 min to 5 minutes.

-Maulik



On Jan 29, 2020, at 2:44 PM, ARWattam <notifications@github.com<mailto:notifications@github.com>> wrote:


The following genomes produce an error when a user tries to cluster them on the Protein Family Sorter. Maulik thinks it is timing out, but this shouldn't happen:
1392.242
1392.324
1392.379
1392.635
1392.642
1412842.4
1428.425
226900.8
260799.14
261594.21
281309.8
288681.15
347495.3
405535.8
412694.7
451709.7
486624.3
526970.3
526979.3
526985.3
527022.3
527028.3
527029.3
527032.3
572264.4
637380.6
86661.165
