### ISSUE TITLE
Wrong Representative genome on the Brucella page

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#2400]
Why is Ochrobactrum listed as a representative genome on the Brucella genus page.  It would be appropriate one level up.
<img width="633" alt="Screen Shot 2021-02-25 at 4 08 57 PM" src="https://user-images.githubusercontent.com/11475316/109217524-f2a12400-7783-11eb-8696-f79345d0caa0.png">

**Comment by hyoo** [comment]
![image](https://user-images.githubusercontent.com/1236467/109220300-59234380-777e-11eb-8dad-ae6e2fb57cce.png)
because it belongs to the "Brucella intermedia" species. Not sure whether it is a legitimate species, but we have some other genomes in there. 
https://patricbrc.org/view/Genome/641118.3
https://patricbrc.org/view/Taxonomy/94625

**Comment by ARWattam** [comment]
Okay, that at least is an explanation.  I am going to build a tree and see if it really is part of Brucella, which I doubt.  But glad to know it is not our fault

**Comment by ARWattam** [comment]
<img width="873" alt="Screen Shot 2021-02-26 at 11 05 23 AM" src="https://user-images.githubusercontent.com/11475316/109324363-92ad8a80-7822-11eb-94cc-8f30557e77e4.png">
See, its not Brucella, but not our problem

**Comment by mshukla1** [comment]
NCBI taxonomy is messed up for this species. I don't think there is much we can do. 

<img width="518" alt="Screen Shot 2021-06-22 at 3 54 41 PM" src="https://user-images.githubusercontent.com/1236463/122998084-3a227000-d372-11eb-85cf-a8370f8a496d.png">
