### ISSUE TITLE
Data: Private genome-protein begins with ARL

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#246]
Obviously something is very wrong
![screen shot 2015-06-05 at 3 15 59 pm](https://cloud.githubusercontent.com/assets/11475316/8013253/e0e1cb08-0b95-11e5-8f01-a7adebeaf355.png)

**Comment by mshukla1** [comment]
As discussed, it is a partial gene predicted by Prodigal at the beginning of the chromosome. Prodigal (and other gene prediction programs) have option for predicting partial features near the contig boundaries. The advantage of having this option on is that you get the partial/truncated genes, which otherwise would be considered absent in the genomes. Disadvantage is that, you may end up having genes with non-canonical start codons, and partial/truncated gene/protein sequences, which may create noise in protein families and MSA/tree. 

There is an ongoing discussion in a separate email thread about whether to annotate partial genes or not as part of default option in rasttk.

**Comment by olsonanl** [comment]
Good timing; I'm also taking on the issue of genes annotated across annotation gaps. Genes truncated across contig ends are related. What I'm probably going to do is populate the partial start / partial stop fields that are in genome object. We'll need to figure out what to do with this data on the website.

**Comment by mshukla1** [comment]
#376 duplicate
