### ISSUE TITLE
Can't save genome group on public site

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#252]
I have created a new group and it doesn't appear in the protein family sorter or the comparative pathway tool

**Comment by hyoo** [comment]
If you have a genome group with your private genome, current production site will be failed to give you a list. This is due to the fact that we're sharing workspace between beta and prod, and production cannot recognize the private genome. You need to delete that genome group if you want the list back. Sorry.

**Comment by mshukla1** [comment]
The genome groups are created correctly, just not displayed in the searches and tools.  We discussed this in the sync call yesterday, and decided not to take any actions. When we make the release, the problem will be solved. 

Please report if you see the problem after the release.
