### ISSUE TITLE
Compare region view-selected gene not shown

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#257]
Brucelles suis 1330 wbkB gene on the beta site.  When I click on the compare region view, 5 genomes appear, but not suit 1330
![screen shot 2015-06-09 at 7 22 41 am](https://cloud.githubusercontent.com/assets/11475316/8056683/833c407e-0e78-11e5-8f23-522ab7863bfd.png)

**Comment by mshukla1** [comment]
Harry, when I display only 5 genomes, the Brucella suis 1330 do not appear. However, when I select 10 or more genomes, it appears at the top. Can you please check if the problem is because of the parsing on your side or related to API? 
![screen shot 2015-06-09 at 12 11 29 pm](https://cloud.githubusercontent.com/assets/1236463/8063011/dcf4aac0-0ea0-11e5-96e3-ca14cb7fa780.png)

**Comment by mshukla1** [comment]
Another related issue: for some tracks, I am getting errors. My guess is that, most likely, it because those genomes are not available in PATRIC?!
![screen shot 2015-06-09 at 12 14 03 pm](https://cloud.githubusercontent.com/assets/1236463/8063131/23833a10-0ea1-11e5-8bba-b0097057f2b7.png)

**Comment by olsonanl** [comment]
That first track in error, for Brucella melitensis bv. 1 str. M111, is a genome in patric. I ran the query programmatically and it appears to be returning valid data.

—bob

On Jun 9, 2015, at 11:14 AM, mshukla1 <notifications@github.com<mailto:notifications@github.com>> wrote:


Another related issue: for some tracks, I am getting errors. My guess is that, most likely, it because those genomes are not available in PATRIC?!
[screen shot 2015-06-09 at 12 14 03 pm]<https://cloud.githubusercontent.com/assets/1236463/8063131/23833a10-0ea1-11e5-8bba-b0097057f2b7.png>

**Comment by hyoo** [comment]
Bob, it seems like, SAP does not return any feature for these three genomes.
Here is a part of raw result from SAP,
...
            "features": [],
            "genome_id": "1004955.3",
            "genome_name": "Brucella melitensis bv. 1 str. M111",
            "pin": "fig|1004955.3.peg.3335",
            "row_id": 14
        },
        {
            "features": [],
            "genome_id": "1004956.3",
            "genome_name": "Brucella melitensis bv. 1 str. M28-12",
            "pin": "fig|1004956.3.peg.3335",
            "row_id": 15
        },
        {
            "features": [],
            "genome_id": "1004957.3",
            "genome_name": "Brucella melitensis bv. 1 str. M5",
            "pin": "fig|1004957.3.peg.3339",
            "row_id": 16
        },
...

**Comment by hyoo** [comment]
anyway, I have added a check to skip genomes that do not have any feature.
fixed and available on beta.

**Comment by olsonanl** [comment]
Can you send me the corresponding sap query ? When I ran one against a different peg I was getting feature data.

________________________________

**Comment by mshukla1** [comment]
Harry, for the same gene, I don't see anything in compare region view now!!!
https://www.beta.patricbrc.org/portal/portal/patric/CompareRegionViewer?cType=feature&cId=PATRIC.204722.5.NC_004310.CDS.517393.518247.rev&tracks=&regions=5&window=10000&loc=1..10000
![screen shot 2015-06-10 at 8 38 43 am](https://cloud.githubusercontent.com/assets/1236463/8082611/81cc746e-0f4c-11e5-869d-0b5d283d6645.png)

**Comment by mshukla1** [comment]
Checked, again. It is working now and suis 1330 is at the top. Thanks.
