### ISSUE TITLE
Workspace messed up!!!

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#262]
I don't see anything in my workspace home in beta. I LOST EVERYTHING!!! ;)

![screen shot 2015-06-10 at 8 45 23 am](https://cloud.githubusercontent.com/assets/1236463/8082734/58151b8e-0f4d-11e5-986f-6eb31a893dce.png)

**Comment by rkenyon** [comment]
Mine is empty as well.

**Comment by dmachi** [comment]
We reported this to bob last night. p3c and p3 services seem to not be responding this morning.

Dustin

**Comment by olsonanl** [comment]
There is apparently a plague among the SEED systems. Three are not responding in ganglia. Beech still is but I cannot log in.

It started with elm showing very high loads due to RAiD disk resync; I don't know if something similar is happening on the others. I have a ticket in with systems on this.
________________________________

**Comment by mshukla1** [comment]
The workspace server is back up. Workspace browser seems fine now.
