### ISSUE TITLE
The file and folder generation time is a few hours and minutes faster than local time 

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#292]
For example, I uploaded a file at 3:40 pm EST and file time says 6:52PM.

**Comment by dmachi** [comment]
The hours might be off because of the date/time being expressed in UTC.  The minutes are probably due to incorrect time on the Workspace and/or shock servers since the power outage/reboot.  I've checked the p3-prod servers at VBI and the date/time look to be correct (and the date/time comes from the workspace in any case)

**Comment by olsonanl** [comment]
Hm, ntp running on the collection of servers at ANL and times appear to be correct. Will need to check further.

**Comment by chmao1** [comment]
Appears to be correct now.
