### ISSUE TITLE
rockhopper inconsistent results

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#340]
At the florida workshop, the users became aware that running rockhopper multiple times with the same input resulted in different output. This is a little strange because alignment doesn't seem like it should have any sort of random sampling. Non-repeatable experiment processing made everyone a little uneasy.  @levinas @brettin @olsonanl

**Comment by olsonanl** [comment]
Vastly different or slightly different?

This may be similar to the velvet changes if any of the rockhopper algorithms are using parallelism and the nondeterminism that may be introduced there.

—bob

On Jul 14, 2015, at 1:46 PM, Andrew Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


At the florida workshop, the users became aware that running rockhopper multiple times with the same input resulted in different output. This is a little strange because alignment doesn't seem like it should have any sort of random sampling. Non-repeatable experiment processing made everyone a little uneasy. @levinas<https://github.com/levinas> @brettin<https://github.com/brettin> @olsonanl<https://github.com/olsonanl>

**Comment by brettin** [comment]
Rockhopper is definitely making use of parallelism as we know.

**Comment by aswarren** [comment]
One thing we have been able to determine so far is that the order of that the reads/conditions is specified matters and will generate different results. If you specify in the same order you get the same results.

This manifests elsewhere but it is easiest to see in the *_summary.txt files
Here we have same data but specify the pairs/conditions in different order.

Exactly the same as the PDF how-to gives:
Computing transcript boundaries...
	Number of 5'UTRs:			431
	Number of 3'UTRs:			179
	Number of predicted RNAs:			2880
	Number of predicted RNAs (not antisense):		1734
	Number of predicted RNAs (antisense):		1146
Computing differential gene expression...
	Number of differentially expressed protein coding genes:	111
Computing likely operons...
	Number of gene-pairs predicted to be part of the same operon:	1253
	Number of predicted multi-gene operons:		685

The reverse order of the how-to:
Computing transcript boundaries...
	Number of 5'UTRs:			443
	Number of 3'UTRs:			187
	Number of predicted RNAs:			42
	Number of predicted RNAs (not antisense):		19
	Number of predicted RNAs (antisense):		23
Computing differential gene expression...
	Number of differentially expressed protein coding genes:	173
Computing likely operons...
	Number of gene-pairs predicted to be part of the same operon:	1173
	Number of predicted multi-gene operons:		662

**Comment by aswarren** [comment]
If you would like to see the rnaseq results in:
 https://www.patricbrc.org/workspace/workshopdemo@patricbrc.org/home/rnaseq

email me for the credentials of username "workshopdemo"

**Comment by olsonanl** [comment]
Giving to fangfang; I'm thinking it may just be the case that we get mildly different output, or if we want users to get absolutely consistent output (perhaps at a performance penalty) we might have a recipe that has that option. I don't have a strong opinion either way.

**Comment by rkenyon** [comment]
Will revisit during Jam session.  If it can't be resolved relatively easily, will need to decide if we keep making it available.

**Comment by aswarren** [comment]
Rockhopper issues have been found to be minimal. The differences in Rockhopper runs were magnified by a Differential Expression bug which has been fixed
