### ISSUE TITLE
Workspace-Gene ID appears empty in summary box

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#377]
The B. ovis genome is not private.  I like to capture the peg id from the summary box as I can't cut and paste from the table.  When I look at the summary box while in the Features, I see that the geneID is listed as 0.  Usually it has the peg ID there.
![screen shot 2015-08-05 at 12 57 16 pm](https://cloud.githubusercontent.com/assets/11475316/9092070/cfa847a2-3b71-11e5-8ca7-1c09dc1d826d.png)

**Comment by ARWattam** [comment]
Actually, belay that.  I guess when I found the peg in there, that was the unusual case.  I'll try to repeat it.

**Comment by mshukla1** [comment]
gene_id refers to the NCBI/GenBank gene id. For some reason, when it is not present, it got stored in the database as zero instead of null. 

In any case, It should not have peg id in there.

**Comment by mshukla1** [comment]
There are many cases where if gene id and gi numbers (and probably other numeric identifiers) where null, they got stored as 0 in the database. This may be slightly confusing but there are no side effects or unintended consequences here. Hence, instead of updating millions of records in the database, I am leaning towards of leaving them as it is in the database, unless someone disagrees. 

-Maulik
