### ISSUE TITLE
Update the WordPress version

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#394]
Will need to synchronize with what is in the Beta website, then update from there and see what problems arise.

**Comment by hyoo** [comment]
I have updated all three (patricenews-dev.vbi.vt.edu, patricenews-test.vbi.vt.edu, and patricenews.vbi.vt.edu) instances to 4.3.1 (most updated version as now Sep 22, 2015). 

I have tested all custom php files and found all working fine. Please test whatever you think relevant. 

I also removed some unnecessary themes in order to keep the wordpress simple & easy to upgrade.

All three are synchronized to github.com (https://github.com/cidvbi/patric-enews). However, we should review it carefully before we make the repo public, since some config files contains credentials.
