### ISSUE TITLE
Private genome-Feature table and download not in gene order

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#425]
The feature table is not showing, or downloading the pegs in the order they occur in the genome.  Because of the way the peg ids are labeled (peg.1 as opposed to peg.0001), it is impossible for users to sort on this column and get the actual order. This creates quite the nuisance to the researcher using the site.   If the genome has been annotated by GenBank (private genomes have NOT been, bts), the user can use those ids to sort, but we obviously don't want to rely on that!We either need to add a column for the number the gene is in the genome, or change the peg to peg.0001. 
![screen shot 2015-09-02 at 6 52 01 pm](https://cloud.githubusercontent.com/assets/11475316/9646711/253ee840-51a4-11e5-8121-ae374b7038ea.png)

**Comment by olsonanl** [comment]
Can’t you do this by sorting by start or end position? (You’d actually need to sort by contig + start I guess).  Hm.

On Sep 2, 2015, at 5:56 PM, ARWattam <notifications@github.com<mailto:notifications@github.com>> wrote:


The feature table is not showing, or downloading the pegs in the order they occur in the genome. Because of the way the peg ids are labeled (peg.1 as opposed to peg.0001), it is impossible for users to sort on this column and get the actual order. This creates quite the nuisance to the researcher using the site. If the genome has been annotated by GenBank (private genomes have NOT been, bts), the user can use those ids to sort, but we obviously don't want to rely on that!We either need to add a column for the number the gene is in the genome, or change the peg to peg.0001.
[screen shot 2015-09-02 at 6 52 01 pm]<https://cloud.githubusercontent.com/assets/11475316/9646711/253ee840-51a4-11e5-8121-ae374b7038ea.png>

**Comment by ARWattam** [comment]
Yes, you could do that but it is hardly intuitive.  Just imagine that you are a naive research biologist and you are NOT allowed to use your terminal.  How long would it take you to figure this out? Even I got screwed up on this just this a couple days ago, as the table is not downloading showing everything in the correct order (which it used to do!!!).  I think we should be trying to make things easier for people, which RAST did very well.   At least when I annotate something at RAST and download the file, it would give me a column with the gene order.  Or it used to...maybe that has been phased out.

**Comment by olsonanl** [comment]
Yup, I agree. They should come up in that order. (I submitted exactly the same complaint against KBase btw).

On Sep 3, 2015, at 10:32 AM, ARWattam <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, you could do that but it is hardly intuitive. Just imagine that you are a naive research biologist and you are NOT allowed to use your terminal. How long would it take you to figure this out? Even I got screwed up on this just this a couple days ago, as the table is not downloading showing everything in the correct order (which it used to do!!!). I think we should be trying to make things easier for people, which RAST did very well. At least when I annotate something at RAST and download the file, it would give me a column with the gene order. Or it used to...maybe that has been phased out.

**Comment by ARWattam** [comment]
Then we are kindred spirits, Bob Olson, united in the desire to make the world a better place for the research biologist.

**Comment by hyoo** [comment]
This is specific to outdated website.
