### ISSUE TITLE
NA sequence not found when clicking on protein in compare regions

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#46]
If you click on a feature in compare regions you get

Feature Details

fig|1403831.3.peg.12 | BN896_0013 | dnaK
Chaperone protein DnaK
CDS: 4041 .. 5958 (+)
NA Sequence

reference sequence not available

Should the sequence be available?

**Comment by hyoo** [comment]
Due to the current implementation of JBrowse, providing na sequence is very complicated. To describe a little more detail, JBrowse requires a whole sequence and it will cut and paste according to the coordination. In addition to that, we also re-calcuate gene coordinations when compared genes are not aligned. We can come up with some work arounds, but we dropped this functionality in low priority.

**Comment by olsonanl** [comment]
That's fine; we should take the text off the popup then.

________________________________
