### ISSUE TITLE
genome ID from search bar

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#489]
This is more of a pet peeve but it happens to me all the time.  If I search based on genome ID, I get back a list of genomes but I can't see their genome ID's so I have to click through the whole list to figure out which one is correct. 

<img width="843" alt="screen shot 2015-09-30 at 10 58 09 am" src="https://cloud.githubusercontent.com/assets/7661533/10198577/41efca9e-6762-11e5-96de-ff6659c9d54d.png">

**Comment by dmachi** [comment]
I was under the impression that for any one genome id there should be exactly one genome in the database, so it seems strange that more than one thing is returning from your search.  I'm seeing the same behavior, so not doubting you, its just weird.

**Comment by dmachi** [comment]
So the issue is that 1313.2310 ends up searching for records with both 1313 and 2310.  If you want to search for the specific id, you can double quote it ... "1313.2310" as the search, and it will return that single result.  There are probably good reasons why the search happens this way, but I'm not sure.

**Comment by olsonanl** [comment]
IMHO the search should be first recognizing the known id formats and doing explicit lookups on those. We know \d+\.\d+ is a genome; we know fig\|\d+\.\d+\.[a-z]+\d+ is a fid, etc.

On Sep 30, 2015, at 11:30 AM, Dustin Machi <notifications@github.com<mailto:notifications@github.com>> wrote:

So the issue is that 1313.2310 ends up searching for records with both 1313 and 2310. If you want to search for the specific id, you can double quote it ... "1313.2310" as the search, and it will return that single result. There are probably good reasons why the search happens this way, but I'm not sure.

**Comment by dmachi** [comment]
I agree and we'll try to do something like that in the new search.

**Comment by hyoo** [comment]
this is specific to outdated website.
