### ISSUE TITLE
Perfect families in Protein Family Sorter not working

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#563]
Perfect families do not seem to be meeting the criterion presented on the PFS.  See screenshot below:
![screen shot 2015-12-08 at 11 58 12 am](https://cloud.githubusercontent.com/assets/11475316/11663715/5a0fc6fc-9da3-11e5-8e1d-e11f6eda5395.png)

**Comment by mshukla1** [comment]
The perfect protein families here means protein families that contain at the most one protein per genome, 
or that a family does not have more than one proteins per genome (paralogs or multiple gene fragments).

However, it does not mean all the genomes selected are present in that protein family (i.e. core genome), hence you see singletons and doubletons as well. 

This this not a bug or something new, this is the same definition we have used since we launched PFS first time in PATRIC1. 

-Maulik
