### ISSUE TITLE
typo (KiB) for size in workspace

### ISSUE THREAD

**Issue by maovt** [PATRIC3/patric3_website#57]
In workspace, the size column for folders and files uses "KiB" instead of KB
![screen shot 2015-03-17 at 3 20 59 pm](https://cloud.githubusercontent.com/assets/6361802/6695766/13f28a16-ccba-11e4-9201-1877b3ab4206.jpg)

**Comment by dmachi** [comment]
These were technically correct, see the following code snippet we were pulling in:
    var thresh = si ? 1000 : 1024;
    if(bytes < thresh) return bytes + ' B';
   var units = si ? ['kB','MB','GB','TB','PB','EB','ZB','YB'] :['KiB','MiB','GiB','TiB','PiB','EiB','ZiB','YiB'];

So basically if we're using 1000 bytes to represent a Kilobyte instead of 1024, the units reflected this. 

However, I understand most people won't get it and be confused, so I've forced it to the 1000 byte threshold (e.g., kB, MB, GB.....)
