### ISSUE TITLE
Variation Service

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#584]
We will introduce a new variant-calling service for closely related genomes. We will
enable the reference genome to be derived from public genomes, raw reads assembled
and annotated by PATRIC services, or genomes uploaded to the user’s workspace. The
service will generate a summary of DNA-level differences among the genomes and
output detailed lists of SNPs, MNPs, insertions and deletions with confidence scores.
The service will provide annotations on the SNP effect such as “the SNP is in a coding
region” and “results in an amino acid change”. The service will identify regions present or
absent when comparing the reference genome to reads in the raw read data.

**Comment by rkenyon** [comment]
Per Tom, service is running now in prototype mode.  Need to migrate to production, and will require some UI work.  Initial plan is to display results via genome browser and have downloadable vcf files.

**Comment by rkenyon** [comment]
3/28: Initial UI for submission FASTQ is up on beta.  Fangfang issued pull request.  Andrew will send app spec to Bob to review.

**Comment by levinas** [comment]
@aswarren: I have added 'mapper' and 'caller' parameters to the [spec file] (https://github.com/levinas/app_service/blob/master/app_specs/Variation.json), although I'm still thinking if we need to expose them (instead of recipe) in the UI.

Tools supported:
mapper: bwa-mem, bwa-mem-strict, bowtie2, mosaik, or last
caller: freebayes or samtools
SNP annotator: in-house tool and snpEff

If we go with a single recipe parameter, it will be taken to mean the mapper option, and the variant caller will always be set to freebayes.

**Comment by rkenyon** [comment]
3/31: Harry will put Variation Analysis menu item in JBoss and WordPress.  Andrew will add the one for P3 web.
