### ISSUE TITLE
Genome Annotation, cant select correct taxon name

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#589]
Trying to run the usual workshop usecase of annotating couple of Acinetobacter baumannii genomes using the annotation service. 

I want to select "Acinetobacter baumannii" as the taxon rank, without knowing the taxon id, 
however, app won't let me do it. Two problems.

1. If I type Acinetobacter baumannii, the species doen't show up at the top in the suggester. 
2. If I just type the correct taxon name myself and try to leave the box, it automatically selects the top one in the list, which in this case is "Acinetobacter baumannii VEB". 

...if the UI can't suggest the right name, at least it should not prevent me from using it on my own! 

This has been bugging me since the last two workshops, needs to be fix soon. 

-Maulik

**Comment by olsonanl** [comment]
On a related note - the fields in the upload box don’t match what is generated for the job. Notably, the “genome name” field is given double duty as the name of the job in the workspace and as the scientific name in the generated genome. The “taxonomy rank/name” which is the correct scientific name is not propagated to the job. This results in strange behavior (in particular, PLfams don’t get called unless someone replicates the scientific name in the genome name field) and doesn’t let one name genome output by anything but genome name.

We need to fix this interaction...

On Feb 25, 2016, at 6:30 AM, mshukla1 <notifications@github.com<mailto:notifications@github.com>> wrote:


Trying to run the usual workshop usecase of annotating couple of Acinetobacter baumannii genomes using the annotation service.

I want to select "Acinetobacter baumannii" as the taxon rank, without knowing the taxon id,
however, app won't let me do it. Two problems.

  1.  If I type Acinetobacter baumannii, the species doen't show up at the top in the suggester.
  2.  If I just type the correct taxon name myself and try to leave the box, it automatically selects the top one in the list, which in this case is "Acinetobacter baumannii VEB".

...if the UI can't suggest the right name, at least it should not prevent me from using it on my own!

This has been bugging me since the last two workshops, needs to be fix soon.

-Maulik

**Comment by aswarren** [comment]
@mshukla1 this represents the last remaining issue with the taxonomy selector widget. It has to do with the SOLR ordering of results (it needs to promote exact matches). Essentially to fix this I need you or @hyoo to add a copy field in the taxonomy table that will allow me to promote the exact match of "Acinetobacter baumannii" to the top. [http://lucene.472066.n3.nabble.com/How-to-boost-exact-match-td4015862.html](url) As a stop-gap for this problem I modified the search box to support typing the rank. e.g. if you type "species Acinetobacter baumannii" or "baumannii species" the choice you want rises to the top.
Please add the copy field to taxonomy solr table.
As you know, we need a precise taxonomic rank associated with the genome so that it can be correctly placed in the context of the taxonomy on the rest of the site.

**Comment by aswarren** [comment]
I was able to boost higher order taxon divisions over no-rank and species.
