### ISSUE TITLE
Weird completion date for private genomes

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#596]
Hmm...for some reason it looks like all my private genomes were completed on Dec 31, 1969.  I guess I was quite precocious!
![screen shot 2016-02-29 at 12 09 46 pm](https://cloud.githubusercontent.com/assets/11475316/13402262/835b56b8-dedd-11e5-9d27-aa2b65c471a2.png)

**Comment by mshukla1** [comment]
:)

Yes, I noticed it after the last batch. When the completion date was null, it got converted to 
this weird date. I have made necessary correction in the script, so it won’t happen again. 

I will clean up the genomes already in the system with this date. 

-Maulik

**Comment by dmachi** [comment]
The weird date is being treated as unix time.

Unix time (also known as POSIX <https://en.wikipedia.org/wiki/POSIX> time or Epoch <https://en.wikipedia.org/wiki/Epoch_(reference_date)> time) is a system for describing instants in time <https://en.wikipedia.org/wiki/Time>, defined as the number of seconds <https://en.wikipedia.org/wiki/Second> that have elapsed since 00:00:00 Coordinated Universal Time <https://en.wikipedia.org/wiki/Coordinated_Universal_Time> (UTC), Thursday, 1 January 1970,[1] <https://en.wikipedia.org/wiki/Unix_time#cite_note-single-unix-spec-4.15-1>[note 1] <https://en.wikipedia.org/wiki/Unix_time#cite_note-2> not counting leap seconds <https://en.wikipedia.org/wiki/Leap_second>.

It looks like the null value is being treated as 0.

Dustin

**Comment by mshukla1** [comment]
I have corrected the completion dates in the database as well. You should not see the weird dates any more. 

-Maulik
