### ISSUE TITLE
Why do the RefSeq genes say there is no corresponding PATRIC feature, when there is?

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#597]
Look at the two feature pages for Rv0667.  From the PATRIC side, I can see that it has a peg id.  If I click on the RefSeq id (which users would be inclined to do, as it has more meaning for them than the peg id), they would see that there is no corresponding PATRIC feature.  
![screen shot 2016-02-28 at 12 47 47 pm](https://cloud.githubusercontent.com/assets/11475316/13402415/26ceae3a-dede-11e5-8887-e2fc27605183.png)
![screen shot 2016-02-28 at 12 47 39 pm](https://cloud.githubusercontent.com/assets/11475316/13402416/26cf6bcc-dede-11e5-8621-2f6de187281d.png)

**Comment by hyoo** [comment]
This is fixed on beta. Same issue to #594 
https://www.beta.patricbrc.org/portal/portal/patric/Feature?cType=feature&cId=RefSeq.83332.12.NC_000962.CDS.759807.763325.fwd

**Comment by hyoo** [comment]
Actually, this is another problem. This is due to the fact that subquery to look up PATRIC feature does not work.

https://www.patricbrc.org/api/genome_feature/?and(eq(pos_group,%22NC_000962%3A2727339%3A%2B%22),eq(feature_type,CDS),eq(annotation,PATRIC))
returns null even though there is a corresponding PATRIC feature.

http://harad.vbi.vt.edu:8983/solr/genome_feature/select?q=pos_group:%22NC_000962:2727339:%2B%22+AND+feature_type:CDS+AND+annotation:PATRIC&indent=true

**Comment by hyoo** [comment]
Dustin, fixed data api call and now it seems working fine on beta.

https://www.beta.patricbrc.org/portal/portal/patric/Feature?cType=feature&cId=RefSeq.83332.12.NC_000962.CDS.759807.763325.fwd

This will be deployed to production at the bug-fix release.

**Comment by hyoo** [comment]
I see this issue again on production.

**Comment by mshukla1** [comment]
Fixed on beta.
