### ISSUE TITLE
Browsing for contigs doesn't work

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#600]
I ran the B. melitensis reads through two different assemblers and wanted to annotate. I didn't want to sort through the quick list of contigs but rather to click on the folder to browse.

Unfortunately the assemblies folder where I stored the output shows empty. Here it is in the browse for contigs window:

![screen shot 2016-02-29 at 3 41 03 pm](https://cloud.githubusercontent.com/assets/2152226/13409945/d894fd10-defa-11e5-90a2-25afed911671.png)

but if you look in workspace browser itself we can see the assemblies are indeed there:

![screen shot 2016-02-29 at 3 41 40 pm](https://cloud.githubusercontent.com/assets/2152226/13409978/f8bde502-defa-11e5-86f2-7fc9d45a670b.png)

**Comment by dmachi** [comment]
This is a result of the lack of container objects currently.  The folders actually containing your results are in the hidden folders.  The list you see in the workspace is showing you a list of job result objects.  When you use the drop down, it works because it is listing by type and so doesn’t care whether things are in the hidden folders or not.  That is not to say we can’t fix this, but its not a quick fix either.

**Comment by nconrad** [comment]
Really old ticket, but I think this was addressed by @dmachi recently when he added the "show hidden files and folders" button?

![image](https://user-images.githubusercontent.com/1194246/30290385-c6e855a4-96f4-11e7-8486-c00b11243294.png)

**Comment by mshukla1** [comment]
Yes, indeed. Closing the ticket.
