### ISSUE TITLE
gene list from transcriptomic heatmap page should propagate values

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#627]
when I pick genes to put in a gene list from the heatmap of a transcriptomic data set the gene page that comes up should include the comparison values from the experiment.

**Comment by mshukla1** [comment]
can you explain which page you are referring to? or add a screenshot?

**Comment by olsonanl** [comment]
Start with a differential expression job result.
Go to gene list, select some comparisons.
Click genes button.
You see a feature list that includes up/down values.
Click heatmap.
Select genes. 
Click Show Genes.
You get a gene list that does NOT include up/down values. These should have the values included.

**Comment by mshukla1** [comment]
Because there can be multiple condition related to genes, it is difficult to show them in the dynamic table. 

If you want to see up/down expression values for selected genes, you can download them as tab delimited or excel file from the pop up box. 

<img width="634" alt="screen shot 2017-09-17 at 11 53 33 am" src="https://user-images.githubusercontent.com/1236463/30523043-a0544542-9b9f-11e7-9855-b5bb543071d8.png">
