### ISSUE TITLE
PFS: Clustering function not working on heat map view-Protein Family Sorter

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#654]
Anchoring is working, though

**Comment by hyoo** [comment]
It IS working correctly, though, default clustering param does not right job. 
It may be because default algorithm (Pearson correlation) neglects the differences when you have a very large dataset and does not move rows or columns. 

Try "Uncentered correlation". Click Advanced Clustering -> Clustering algorithm (2nd box). 
This takes longer but works well.

Harry

**Comment by mshukla1** [comment]
I have verified on alpha that clustering is working in general on protein family heatmap. 

@ARWattam, please check it again and share specific example / link if you still see the problem.
