### ISSUE TITLE
Downloads from the workspace keep getting named the same way, makes it impossible to keep track of what you are downloading

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#658]
![screen shot 2016-05-25 at 8 21 09 am](https://cloud.githubusercontent.com/assets/7661533/15541344/ac8573e0-2251-11e6-8ea1-259c130693c2.png)

**Comment by olsonanl** [comment]
Which file did you click on? I wonder if there is a space handling bug in there somewhere

**Comment by jimdavis1** [comment]
Actually for me it didn't matter.  It did it every time I clicked the download icon.

**Comment by nconrad** [comment]
This is pretty old, but could you look into it, @zreyn?  reassign to me if needed.

**Comment by mshukla1** [comment]
The annotation files are named by genome name given at the time of submission and the whole file name is kept when it is downloaded, i.e. it doesn't get truncated at space. If you download the same file multiple time, it will be downloaded with the same name, and your browser will keep adding numbers at the end to make them unique.  So, I think download from annotation job results is working as expected. 

If you are  talking about downloads from the tables, the files are labeled by the page you download it from, i.e. PATRIC_genome, PATRIC_feature, etc. It is hard to make them more specific because the data can be downloaded from any context / scope / filters. We expect users to change the name as they prefer using browser download window before saving them on their machine. 

-Maulik
