### ISSUE TITLE
Taxonomy tab: some taxon nodes do not show children

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#753]
example: Brucella / Brucella abortus

https://www.alpha.patricbrc.org/view/Taxonomy/118882

There are many taxonomy nodes with genomes labeled as "no rank", which are not displayed as subtree. 

However, they are displayed correctly on the production website. 

-Maulik

**Comment by dmachi** [comment]
The queries descend down to find the next possible rank.  However, it was terminating the recursion when it hit an item with taxon_rank == species or no rank.   I changed things for species, but cannot do the same with no rank without causing problems.  If we want to be able to descend into a "no rank" item, we'll probably need the parent id on the taxons discussed in another ticket.  Additionally, since we query at each level and there will be no way to predict whether a node _should_ be able to expand (and have a little expansion triangle beside it).  If this doesn't annoy anybody, then we can leave it.  Otherwise we'll need to add a field to know whether a node should be expandable (before querying it).

**Comment by dmachi** [comment]
Fixed
