### ISSUE TITLE
Global Search: Need to return more relevant/specific results in Search

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#777]
3.1.118alpha
When searching for a very specific peg ID, gene name, strain name, etc., the top hits should be exact matches.  Users would like to quickly get to the specific data they want using identifiers they are used to using.

**Comment by dmachi** [comment]
I've changed things to sort the search results by score, so this is hopefully a little bit better now.  It may still require additional score boosting in SOLR. Assigning to Maulik to evaluate.

**Comment by mshukla1** [comment]
I tried many different examples of gene names, locus tags, strain names, and function that I can think of. For most part I am satisfied with the top results. 

Searching for peg ids / patric ids is bit of a problem (i.e. fig|83332.12.peg.1), because behind the scene, it gets split on all alphanumeric boundaries, resulting in many false positive matches and messing up the scores. 

@dmachi, After trying several different search strategies, I have two specific suggestions to address this situation: 
1.  Specific solution for patric ids: whenever search term is a single word and starts with "fig|", search it with double quotes, i.e. "fig|83332.12.peg.1", which will give only the matching feature.
   We can have similar special logic for genome ids as well (\d+.\d+). 
2. More general solution for all ids, locus tags, strain names, gene names etc: whenever search term is single word, search it with and without double quotes, i.e. "fig|83332.12.peg.1" OR fig|83332.12.peg.1. This will give results similar to the original search term, except boost the score for exact match and elevate it to the top. 

Above solutions may not address all search related issues, but will definitely help address some of the most common complains we get from the users. 

-Maulik

**Comment by mshukla1** [comment]
#783

**Comment by chmao1** [comment]
This is fixed.
