### ISSUE TITLE
pseudogenes

### ISSUE THREAD

**Issue by vvons** [PATRIC3/patric3_website#804]
The search for the pseudogene fig|1520703.3.pg.50 with it's ID does not return anything.

**Comment by dmachi** [comment]
Was this against production or against the alpha site.  I am getting results against alpha

<img width="1411" alt="screen shot 2016-07-26 at 9 30 47 pm" src="https://cloud.githubusercontent.com/assets/190574/17162097/5ef685a8-5378-11e6-9ac0-344dfa70589f.png">

**Comment by vvons** [comment]
It was against the alpha and now that I'm logged in but still do not see what you see.

**Comment by mshukla1** [comment]
I see it now. I think it could be because earlier global search shown only CDSs. 

I submitted a ticket to show non-CDS features as well, which may have fixed the problem. 

On a related note, we decided to show PATRIC peg id, in addition to product, so that we don't end up with "undefined" when a feature doesn't have product.
