### ISSUE TITLE
Taxonomy Overview does not use applied filters

### ISSUE THREAD

**Issue by dmachi** [PATRIC3/patric3_website#822]
When you apply filters to a taxonomy, the overview page does not update to reflect.  Maybe we don't care.

**Comment by hyoo** [comment]
this is due to the fact that we started using taxon_id instead of this.state.search where it contains all the genome ids. now I am checking whether the counted genome ids are equal to the taxonomy genome count and if not, will add an extra query param (this.state.search)

will be available soon on alpha. please reopen if you have a concern.

**Comment by dmachi** [comment]
I figured this was the case.  The easiest way to do this is to still use state.search, but make sure that the state.search passed into overview is the taxon_id query instead of the list of id’s query.
