### ISSUE TITLE
copy/paste from table

### ISSUE THREAD

**Issue by aswarren** [PATRIC3/patric3_website#841]
I think it would be great if I were able to select text in a table and copy it.
Is there a dojo table option to enable/detect click and drag?
Its really tough to see a valuable piece of information and not be able to copy it off the screen.

**Comment by dmachi** [comment]
Can you not copy it from the item detail panel? 

I’ve been trying to reserve that operation on the table itself for drag and drop in the future.

**Comment by mshukla1** [comment]
I often like to select and copy ids from one column and use it in another search or tool. 
Alternate is to download the entire table in excel, find the records of interest again, and then copy them, which is very cumbersome! 

This was a much desired table functionality that was added to extjs grid after much effort. We should try to preserve that functionality. 

-Maulik

**Comment by dmachi** [comment]
Yes I understand and plan to allow for doing that operation.

**Comment by hyoo** [comment]
@zreyn I guess this is what you demo last sys-dev call. just to give you the context.

**Comment by hyoo** [comment]
This has been deployed to alpha. However, I have some concerns like below,

- copy with full table option 
1. column order is random. users will complain. basically, difficult to find what you want. 
2. we need some control. for example, we don't want to show segment, owner, etc

- copy with selected columns option
1. I don't know where I can "select" columns
2. I thought I would get whatever I am seeing in the grid. but it returned only four columns. product, patric id, genome name, genome id. I understand these are most used columns. maybe better name?

**Comment by zreyn** [comment]
For full table:

1) Not random exactly, but in the order of the keys in the selected items.  We could sort, but I don't think alphabetical is really what a user would want to see either.  I'm guessing that this is defined somewhere already to show the grid / in the plus button drop down.  I'll see if I can find it to apply the same ordering.

2) We can create a "black list" of keys that we don't want to get into the clipboard and filter those out.  Basically, copy applies to the following types, which we'd need to look at to find the fields we don't want to put on the clipboard:
validContainerTypes: ["genome_data", "sequence_data", "feature_data", "spgene_data", "spgene_ref_data", "transcriptomics_experiment_data", "transcriptomics_sample_data", "pathway_data", "transcriptomics_gene_data", "gene_expression_data", "interaction_data", "genome_amr_data"]

For copy with selected columns:

1)  "Selected" means what is shown in the grid (versus showing another set of checkboxes like the one in the plus button on the grid).  They are in the order of the keys instead of what is shown, which is kind of annoying, but you should get only those columns visible.  

2) All examples I've tested have worked, but if you have an example where there are visible columns not copied, let me know.  There might be a name mismatch between the object keys and the columns or something.

**Comment by zreyn** [comment]
Looks like I can pull columns and orderings from here:
https://github.com/dmachi/p3_web/blob/master/public/js/p3/widget/ColumnsGenome.js

I'll also put the makings of a 'black list' of columns not to show.  I like a white list better since we're already looking up columns for ordering, but I doubt people will remember to add stuff to it when new columns show up.

**Comment by zreyn** [comment]
Not sure we need the blacklist with the shown columns option, so leaving that out for now.
[PR568](https://github.com/PATRIC3/p3_web/pull/568)

**Comment by zreyn** [comment]
Added blacklist of columns: https://github.com/PATRIC3/p3_web/pull/574

**Comment by hyoo** [comment]
i found a bug, but i will create another ticket, since the original request has been met already.
