### ISSUE TITLE
Correlated genes showing misc features for reference genome on public site

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#862]
I was looking at the correlated genes for fig|511145.12.peg.277  on production and was surprised to find that misc features, interspersed with the genes, are appearing.  I think it should be just genes.
![screen shot 2016-08-19 at 10 52 19 am](https://cloud.githubusercontent.com/assets/11475316/17813897/454bfa80-65fb-11e6-9253-68371687329c.png)

**Comment by mshukla1** [comment]
There are two problems here: 

1. There are genes from other genomes being shown here, because they have the same locus tag as the reference MG1655 genome. 
The correlated genes should be computed for the genes for the same genome, using genome id as one of the conditions. 

2. Non-CDS features are shown under correlated genes. A filter can be applied to get only CDS features!  
However, I think it might be useful, specially for the data from RNA-Seq experiments, to find correlation 
between CDS and non-CDS features, i.e. RNAs. 

-Maulik

**Comment by mshukla1** [comment]
The same problem on the alpha site as well. 

https://www.alpha.patricbrc.org/view/Feature/PATRIC.511145.12.NC_000913.CDS.288525.289529.rev#view_tab=correlatedGenes

<img width="1435" alt="screen shot 2016-08-24 at 1 22 39 pm" src="https://cloud.githubusercontent.com/assets/1236463/17942655/e8a8fe70-69fd-11e6-9cef-9264346606f0.png">

**Comment by mshukla1** [comment]
Verified fix on alpha.

**Comment by ARWattam** [comment]
I'm still seeing the same error on production....see attached screenshot.  It does seem to be working on alpha, but I am confused as I am not seeing the same genes in the correlation (see other attached screenshot for alpha).

----- Original Message -----

**Comment by hyoo** [comment]
I am fixing production as well. will be available soon.
