### ISSUE TITLE
Protein family default in alpha needs to be PLFam, not FigFam

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#864]
And its a bit buggy.  Hard to change between radio buttons

**Comment by mshukla1** [comment]
Actually, it is a bit more tricky. 

- If looking at a protein families at a genus level or below, or for genome group/list where all the genomes are from the same genus, it makes sense to show PLFAM as default. 

- However, there are genomes from multiple genera, then PGFAM should be default. 

- If we want to simplify the logic for now, we can make PGFAM default for all cases, instead of figfams. 

-Maulik

**Comment by hyoo** [comment]
will be available on alpha soon.

**Comment by mshukla1** [comment]
For now, it is changed to PGfam. 

-Maulik
