### ISSUE TITLE
Steps in comparing pathways should open up new tabs instead of rewriting page-alpha

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#868]
It frustrating to have to go back and forth.

**Comment by hyoo** [comment]
you mean the pathway summary (aka enrichment)? I should open new tab. please let me know where it doesn't.

**Comment by mshukla1** [comment]
As we discussed, if there are too many features in the selection (from heat map or gene list), it breaks the pathway summary page because there are too many ids to handle in the URL. 

For now, as a short term solution, harry is going to open pathway summary in the same page, so that it works. However, we understand that this may be frustrating to some as it breaks your current view. 

We will revisit this after the beta release. 

-Maulik

**Comment by dmachi** [comment]
This is fixed now for pathway summary.  If there are other tools that should open in a new window, they will need to have their links updated to use topic.publish like:

Topic.publish("/navigate", {href: "/some/long/url", target: "blank"});
