### ISSUE TITLE
annotation app - can't put in a tax id

### ISSUE THREAD

**Issue by olsonanl** [PATRIC3/patric3_website#88]
This is a valid id but it says it isn't and won't let me continue. The app should let someone put in whatever they want.

![screen shot 2015-03-23 at 11 48 43 am](https://cloud.githubusercontent.com/assets/2152226/6785277/a125cc08-d152-11e4-8c5b-23577aed3f52.png)

**Comment by dmachi** [comment]
This one is working for me once I move to the next field.  However there does seem to be some wierdness in the search results.  Will check on it.

Dustin

**Comment by aswarren** [comment]
The invalid message you received for 83333 is probably caused by latency in hearing back from the API. Everything worked fine for me when using that number. I have fixed a bug relative to this and made the field "not required." Though we ought to think about whether we really want to allow invalid tax ids and the difficulties we will have in integration of annotation results downstream with no real world attach points with which to group the data.
