### ISSUE TITLE
Transcriptomics tab: don't need to filter by reference/representative

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#914]
I see the yellow box with the message on the transcriptomics tab: 

"This tab has been filtered to view data limited to Reference and Representative Genomes in your view."

Given that we have only limited number of experiments and comparison, I don't think we need to apply any filters on the transcriptomics tab.

**Comment by hyoo** [comment]
I don't see this happening anymore. Please provide url to reproduce this issue.

**Comment by dmachi** [comment]
This happens when you go to a collection that has >10k genomes.  

https://www.beta.patricbrc.org/view/Taxonomy/1301#view_tab=transcriptomics https://www.beta.patricbrc.org/view/Taxonomy/1301#view_tab=transcriptomics

I think the behavior is appropriate.  The issue isn’t the number of experiments, but rather the number of genomes.
