### ISSUE TITLE
Need to remove login requirement for tools that don't need them

### ISSUE THREAD

**Issue by rkenyon** [PATRIC3/patric3_website#928]
Protein Family Sorter: https://www.beta.patricbrc.org/app/ProteinFamily

Comparative Pathway: https://www.beta.patricbrc.org/app/ComparativePathway

**Comment by dmachi** [comment]
The mechanism for defining whether an app needs authentication has been tested and works.  The problem here is that the BLAST application includes WorkspaceObjectSelector by default, which requires authentication.  When not logged in, the BLAST app fails to load because of this.  This will either need to make the BLAST app dynamically add that field when logged in or do something to WorkspaceObjectSelector so it doesn't break when it can't talk to the workspace.

**Comment by hyoo** [comment]
I am now activating genome group selector after checking user status. This will be available on alpha soon.

**Comment by mshukla1** [comment]
fixed.
