### ISSUE TITLE
GeneMark license has expired

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#943]
I have been working on the new tutorial for Assembly and I found the following text in the downloadable report...do we need to renew this license?
<img width="865" alt="screen shot 2016-09-23 at 12 59 26 pm" src="https://cloud.githubusercontent.com/assets/11475316/18794516/d097ee20-818d-11e6-836b-58a6dc691386.png">

**Comment by olsonanl** [comment]
We ran into this earlier and I raised the issue with Rick since he obtained the license through the UC. I just raised it again.

—bob

On Sep 23, 2016, at 12:01 PM, ARWattam <notifications@github.com<mailto:notifications@github.com>> wrote:

I have been working on the new tutorial for Assembly and I found the following text in the downloadable report...do we need to renew this license?
[screen shot 2016-09-23 at 12 59 26 pm]https://cloud.githubusercontent.com/assets/11475316/18794516/d097ee20-818d-11e6-836b-58a6dc691386.png

**Comment by mshukla1** [comment]
Can we continue to use  it in the annotation service, while we are waiting for the new license?

**Comment by olsonanl** [comment]
No. The license is expired and the tool refuses to run without an updated license.

On Oct 7, 2016, at 1:00 PM, mshukla1 <notifications@github.com<mailto:notifications@github.com>> wrote:

Can we continue to use it in the annotation service, while we are waiting for the new license?

**Comment by mshukla1** [comment]
@brettin, who should we talk to for renewing GenMark license? 

@olsonanl , I talked to Jim, and he thinks GenMark should not be used in the default PATRIC annotation pipeline. 

-Maulik

**Comment by mshukla1** [comment]
Not using genmark any more in PATRIC, closing the ticket.
