### ISSUE TITLE
Protein families don't seem to be loading for private genome in beta

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#957]
I waited for about 5 minutes, and it never loaded
<img width="1363" alt="screen shot 2016-10-02 at 5 01 23 pm" src="https://cloud.githubusercontent.com/assets/11475316/19023676/0127d7ea-88c2-11e6-8476-e82ae0c9ed83.png">

**Comment by hyoo** [comment]
in my case, first load returned 0 result and realized that my genome doesn't have pgfam assignement. when I changed to figfam, it worked. Needs to discuss how to address this issue.

![957_works](https://cloud.githubusercontent.com/assets/1236467/19054489/3907b018-8985-11e6-8f3e-70f35c989995.png)

**Comment by mshukla1** [comment]
This is a sitewide problem....we need the following two things, without that I can't tell whether the search is still running or returned zero results!!
1. Whenever a search is running, we need a wait icon / spinning wheel so that users know they need to wait for results to load. 
2. Whenever a search returns zero results, we need to display a clear message that no results found, please change the search criteria.

**Comment by mshukla1** [comment]
I verified that private genomes are shown in PFS.
