### ISSUE TITLE
Search: specificity and scoring 

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#976]
Version: 3.2.9 beta
URL: 
https://www.beta.patricbrc.org/view/GenomeList/?and(keyword(%22%27Lactobacillus%22),keyword(%22casei%27%22))
User ID: KPNs_4_Houston

I am using the main search bar to search genomes for Lactobacillus casei.
If I search for Lactobacillus casei, I get Lactobacillus paracasei, which 
is fine because it is a generic search.
If I search for "Lactobacillus casei" I still get Lactobacillus paracasei, 
which must be a bug.
If I search for 'Lactobacillus casei' it hangs.

**Comment by mshukla1** [comment]
Dustin, I also noticed that the top results we are getting on the beta site are different those on the public site. The latter seems to be more in line with what I would expect. 

-Maulik

**Comment by dmachi** [comment]
I don't know how to fix this.  The same search ("Lactobacillus casei") in SOLR directly returns the same thing (89 records, including paracasei).  See http://harad.bioinformatics.vt.edu:8983/solr/genome/select?q=%22Lactobacillus+casei%22+&fq=public%3Atrue&sort=score+desc&wt=json&indent=true

So if there is a way to avoid this in solr, please let me know and I will try to fix.

Secondly, the scoring sort was going ascending so that is why paracasei was at the top of the list.  I've changed that to sort descending and so it looks better now  though the paracasei results are still in the list.

I have the score sort order fixed locally, will deploy to alpha later today.

**Comment by dmachi** [comment]
I suspect that the paracasei show up in the search because of the taxon_lineage_ids has  "Lactobacillus casei group" in it.

**Comment by mshukla1** [comment]
Having paracasei show up is fine, as long is desired genomes are at the top. 

I am ok with the default search order returned by solr. 

genome_name
Lactobacillus casei UW4
Lactobacillus casei 12A
Lactobacillus casei A2-362
Lactobacillus casei LOCK919
Lactobacillus casei BL23
Lactobacillus casei DSM 20011 = JCM 1134
Lactobacillus casei KL1-Liu
Lactobacillus casei strain DPC6800
Lactobacillus casei LC2W
Lactobacillus casei W56
Lactobacillus casei LcA
Lactobacillus casei LcY
Lactobacillus casei strain BM-LC14617
Lactobacillus casei 5b
Lactobacillus casei BD-II
Lactobacillus casei str. Zhang
Lactobacillus casei strain 844_LCAS
Lactobacillus casei strain 867_LCAS
Lactobacillus casei strain Lbs2
Lactobacillus casei strain Lc1542
Lactobacillus casei subsp. casei ATCC 393
Lactobacillus casei A2-362
Lactobacillus casei Lc-10
Lactobacillus casei 12A
Lactobacillus casei UCD174
Lactobacillus casei UW4
Lactobacillus casei Lpc-37
Lactobacillus casei 21/1
Lactobacillus casei 32G
Lactobacillus casei CRF28
Lactobacillus casei M36
Lactobacillus casei T71499
Lactobacillus casei UW1
Lactobacillus casei ATCC 334
Lactobacillus casei strain N87
Lactobacillus casei JCM 1134
Lactobacillus paracasei subsp. paracasei JCM 8130
Lactobacillus paracasei COM0101
Lactobacillus paracasei strain 1316.rep1_LPAR
Lactobacillus paracasei strain 1316.rep2_LPAR
Lactobacillus paracasei strain 275_LPAR
Lactobacillus paracasei strain 525_LPAR
Lactobacillus paracasei strain CAUH35

**Comment by dmachi** [comment]
Well i'm not sure if this is the default search order or not, but i have it sorting by score descending (it was sorting by score ascending, which is why paracasei was at the top.  However, the original ticket here indicated that paracasei shouldn't be in the results, and I can't resolve that one as things stand.

**Comment by dmachi** [comment]
Reassigning to @mshukla1 to close when he is satisfied.

**Comment by mshukla1** [comment]
top results look good now. verified on beta.
