### ISSUE TITLE
Feature list: table doesn't refresh after adding columns

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#979]
Version: 3.2.9 beta
URL: 
https://www.beta.patricbrc.org/view/Genome/1224148.3#view_tab=features&filter=and(eq(feature_type,%22CDS%22),eq(annotation,%22PATRIC%22),keyword(DNA-directed))
User ID: KPNs_4_Houston

Often, when I try to add columns to the table it does not refresh.

**Comment by mshukla1** [comment]
I was able to reproduce the problem after clicking the link above. 

-Maulik

**Comment by dmachi** [comment]
I believe this is a problem with our column size definitions.  There is no hard limit on the number of columns.  However, we define some columns to be of fixed size. I believe that when the total size of fixed size columns exceeds the available space, it either doesn’t add or doesn’t show the additional columns.  Other columns still can be added and removed fine.  This occurs on the link in this ticket too.

**Comment by dmachi** [comment]
I was wrong in my previous description/guess.  The problem here is that some fields didn't have a style defined at all.  Any fields that did not have a style defined seemed to disappear when space is at a premium.  I have fixed by assigning a default style to all columns in the feature grid.  Fixed locally, will be up on alpha later today.

**Comment by mshukla1** [comment]
verified on beta.
