### ISSUE TITLE
Scroll bar in black filter area not appearing-working...beta

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#980]
For those of you following the repeat_region drama (why it matched the mcr-1 search term), I solved that.  But in solving that, I found that I was unable to scroll down to see the other feature types.  I finally had to lower the table to see them.  That needs to be fixed.
<img width="474" alt="screen shot 2016-10-05 at 5 32 40 pm" src="https://cloud.githubusercontent.com/assets/11475316/19132556/0b255aa8-8b22-11e6-8792-28184bf9da3c.png">

**Comment by dmachi** [comment]
I haven't been able to reproduce this issue yet.  I do notice that there is a slight bug in that the height calculation for this box is off because of the size increase when things are selected (the bolded orange content takes up more than the white normal content), but that is a different issue from the bars not showing up at all.

**Comment by dmachi** [comment]
Has anybody seen a way to reproduce this reliably?
