### ISSUE TITLE
Created a genome group and it never appeared in my groups

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#985]
A second ago I created a group called Florida mcr-1 protein family, but I never found it in my genome groups, despite clicking on the Created column head.
<img width="1134" alt="screen shot 2016-10-05 at 5 54 45 pm" src="https://cloud.githubusercontent.com/assets/11475316/19133183/ff95747c-8b24-11e6-921c-ad6c2cb2e1e4.png">

**Comment by ARWattam** [comment]
Am I able to create groups on beta?

**Comment by dmachi** [comment]
I just created a genome group without any problems.  Given the name of what you were creating, did you create a feature group instead of a genome group?

**Comment by ARWattam** [comment]
It was from the protein family page
----- Original Message -----

**Comment by dmachi** [comment]
I don’t see a group button on the Protein Families Tab, so I must not be at the correct place.  But my question still remains, wasn’t that a group of features rather than genes and therefore creating a feature group not a genome group.  Have you looked for the group you created in the Feature Groups section of your workspace?

**Comment by mshukla1** [comment]
Rebecca, it seems you may have created a feature group and were trying to find it in genome group. Can you please verify? 

-Maulik

**Comment by dmachi** [comment]
She confirmed this to be the case with me yesterday.
